### ISSUE TITLE
App is crashing, getting null response from server

### ISSUE THREAD

**Issue by vjs3** [omkarmoghe/Pokemap#1]
Application is crashing, response object is null. Check at line 150 in MainActivity.java.

**Comment by omkarmoghe** [comment]
Hmm interesting. I'll take a look in the morning but I should def add null checks etc. Their servers are known to have issues.

**Comment by vjs3** [comment]
Will look into it too once I got time, love to contribute!Thanks.

**Comment by omkarmoghe** [comment]
Awesome! Please do!

**Comment by stunner2002** [comment]
How about taking a 'REST-way' and use a backend to reduce traffic and have a database to rely on in case Niantics server are out of reach? Recoding the existing python project to java would also be obsolete.

**Comment by veonua** [comment]
now it just gets token from Niantics server. no real calls handled.
I can't even find way to make a requests with proto objects

**Comment by omkarmoghe** [comment]
@stunner2002 Right ideally we would have a server/db serve us the data but as of now there is no instance running and we're not sure if Niantic will be more likely to shut it down if we deploy/host a server

@veonua check the getPokemon() methods and READ the readme. We need to translate the proto requests from the main Python library into Java.

**Comment by vjs3** [comment]
@omkarmoghe app was still crashing the reason being you have to enter your username and password in getToken() in MainActivity so in the scenario when it is empty it got crashed, I have fixed that and send you a PR for the same. #13

**Comment by omkarmoghe** [comment]
Yeah this is documented in the readme. You have to add values for that method before building. I'll check out the pr in a sec

**Comment by vjs3** [comment]
Yes sure do that. I will create login screen to make it bit user-friendly to add the username or password in upcoming PR.

@omkarmoghe considering a good amount of discussion is going on as well as development on this repo I would suggest, you should create a gitter channel so that we can discuss the development tasks and issues more easily with each other.

**Comment by omkarmoghe** [comment]
@vjs3 yeah I'll add a discord link for everyone. 

Check out this pr https://github.com/omkarmoghe/Pokemap/pull/12

Has the shared preferences for the username and password. You can build off of that for the login screen 👍

**Comment by vjs3** [comment]
yeah! I will do that, in the mean time you can review my PR.

**Comment by omkarmoghe** [comment]
Yeah will do when I get a chance. At work until this evening

**Comment by vjs3** [comment]
Sure. No problem.

**Comment by omkarmoghe** [comment]
@vjs3 So if you're working on a login screen, I would check for empty username/password there, before passing it to the login method, instead of within the method

**Comment by vjs3** [comment]
Yes. But till now you can use it as I will be doing that after Monday as I
have my exams and then i will make changes accordingly.

Vishwajeet Srivastava
_Google Summer of Code'16 Intern @Mifos_
Contact Number: +91-9783553169
Blog: vishwajeetsrivastava.com
