### ISSUE TITLE
App crashes after attempt to sign in

### ISSUE THREAD

**Issue by markywarkysharky** [omkarmoghe/Pokemap#100]
The app stops running after I try and log in. I have tried multiple versions and many re-installs and nothing seems to be working.

**Comment by markywarkysharky** [comment]
Forgot to mention - I'm running it on an SM-N920W8 on Android 6.0.1

**Comment by MikePT28** [comment]
What account are you using to log in PTC or Google? What do you mean by "many versions"

**Comment by VincentVerdynanta** [comment]
Same.. I'm running dev-rev142, login with PTC, then suddenly it crashes when loading in after pressing "SIGN IN"

**Comment by VincentVerdynanta** [comment]
nvm.. it happens because at the "PTC Username" i fill the email not the username, now it works when i fill the correct username

**Comment by Aldo-f** [comment]
It's only crashes when servers are down (not tested, but is probably the case), or not using correct password/name (tested)

**Comment by markywarkysharky** [comment]
I have used the latest 3 versions as of last night and I'm trying to sign in with ptc. Username and password works fine on Pokemon go - tested on my ipad, also copied and pasted my username and password from notes and still no luck :/

**Comment by Aldo-f** [comment]
dev-rev188
- Crashes after PTC login (servers ar down, give info to user that servers are down?)
- and with Google+ login (servers EU are up). But first "search" (after "found you") lets app crash (it gives the info "searching").

(Sorry if not more helpful, don't have my pc atm)

**Comment by Kolyall** [comment]
Seems we need to add check of " is PTC server work or not" to avoid the same issues like this
