### ISSUE TITLE
WebSpoof App Crashes when Pokemon detected

### ISSUE THREAD

**Issue by Mojo90** [omkarmoghe/Pokemap#101]
Sometimes when a pokemon shows up the app crashes or currently it definetely crashes if I catch a Pokemon --> will be set back to my real location and have to start the app via xcode again.
Is there currently any workaround available? (ios 10 beta3 on iphone 6 plus)

**Comment by MikePT28** [comment]
Xcode & iPhone??? This app is android. 

![](http://img.picturequotes.com/2/3/2166/what-you-talkin-bout-willis-quote-1.jpg)

**Comment by rohanjain1** [comment]
Hahahaha iOS .. you on dope braj?

**Comment by joya0000** [comment]
Not related to pokemap at all...

**Comment by Mojo90** [comment]
oh sorry forget it wrong repo 😂🙈
