### ISSUE TITLE
Project requirements in Readme.md

### ISSUE THREAD

**Issue by ManojMadanmohan** [omkarmoghe/Pokemap#103]
I want to contribute to this in whatever way I can, and I tried to fork this to see and play around with it. However, I realized (after wasting a lot of time) running this app requires:

1) Java version set to JDK 8
2) Android studio canary release 2.2.0

Both of these are not something an android developer would normally have installed on his/her system. This project does not run on the stable release version of android studio 2.1.2. Also, many people may not have java 8 installed on their system and still be running java 7.

It took me hours to figure these things out from the errors that were being thrown out by android studio. I think this is an issue other developers might face as well, and hence I think these requirements should be mentioned in the project Readme

Would be happy to add these myself in the Readme and raise a PR if this makes sense to the maintainer(s)

**Comment by omkarmoghe** [comment]
@ManojMadanmohan hey, sorry you had find out about the version requirement the hard way. we had them written in ther wiki https://github.com/omkarmoghe/Pokemap/wiki/Building but maybe we can try to make that clearer. 

feel free to submit PRs for anything though

**Comment by ManojMadanmohan** [comment]
Do you think there should be a small note or link to this in readme.md?
