### ISSUE TITLE
.

### ISSUE THREAD

**Issue by DaeFolf** [omkarmoghe/Pokemap#109]
.

**Comment by ManojMadanmohan** [comment]
Possibly a duplicate of #96 , which itself is a duplicate of #92

**Comment by omkarmoghe** [comment]
We're currently working on widening the area without getting accounts banned for gps spoofing. stay tuned!

**Comment by botard89** [comment]
Hey. I have been following this for a little bit now, watching progress, and it is all very fascinating. I wanted to personally ask on the subject of radius, there is the python 2.7.X version of something similar to this and was wondering if there might be a feature or optional feature where the steps (-st) could be customized? I like having a whole area to see what is in a town for example. Thanks and awesome job everyone.

**Comment by rohanjain1** [comment]
While it is possible to expand the search area indefinitely, it is not recommended. For now we'll be enforcing a cap on the max searchable area like the py version. If the demand seems strong enough we'll deliberate over a logical way to achieve 'n' step areas, without completely breaking the system.

**Comment by comann** [comment]
Done.
