### ISSUE TITLE
Don't let too many toasts queue up

### ISSUE THREAD

**Issue by vidarr101** [omkarmoghe/Pokemap#113]
One time i was scanning in my area for fun and then closed the program but i kept getting toasts for another 5 minutes because they queued up .

Keep reference of toasts and cancel old ones on new scan.

**Comment by LinkOut** [comment]
Yes, i have noticed that too. I think it only needs to show toast when there are no pokemons on the searched area.

**Comment by tirth1796** [comment]
Can the Toast display length be changed to Short instead of long? It will just enable us to use it faster.

**Comment by jLynx** [comment]
The test needs to be instantly dismissed when another one is sent out. If you cannot or don't want to do it that way, you should use a label that gets updated with the stings instead
