### ISSUE TITLE
Open directions in google maps

### ISSUE THREAD

**Issue by jLynx** [omkarmoghe/Pokemap#120]
**Suggestion:**
Long hold on the selected Pokemon information to open up directions in google maps for when searching for Pokemon that are not in your initial vicinity

**Comment by jLynx** [comment]
Added in #127

**Comment by comann** [comment]
So I'm adding a few features in this enhancement @DarkN3ss61 

1: On the tooltip of the pokemon provide the user with the ability to open Google Navigation.
2: The app should verify that the user can make it to the location before the Pokemon expires.
     (Maybe a first iteration can assume walking....but it would be awesome to also include driving or biking etas).

**Comment by jLynx** [comment]
@comann  I already did this but everyone got shitty at me so I closed the PR
https://github.com/omkarmoghe/Pokemap/pull/127

Apparently it's bad to have it open in Google maps (using to much ram and will stop one of the other apps). Which is a valid point for older devices

**Comment by comann** [comment]
Aight. Then closing this and marking as wont fix.
