### ISSUE TITLE
Relogin never returns

### ISSUE THREAD

**Issue by kyr0** [omkarmoghe/Pokemap#121]
Just login successfully via Ptc. Then tap "Relogin". The NianticManager gets called till the point where:

```
 mAuthInfo = new PtcLogin(mPoGoClient).login(username, password);
```

Is being called. It's a synchronous call that never returns.

**Comment by omkarmoghe** [comment]
fixed in #145?

**Comment by kyr0** [comment]
As far as I tested: yep

**Comment by comann** [comment]
Deprecated. Moving to use a 'Log Out'. Closing Issue.
