### ISSUE TITLE
Google login (The webpage is not availiable) - (Adguard)

### ISSUE THREAD

**Issue by Aldo-f** [omkarmoghe/Pokemap#139]
Google login not (always) working?

Authetification error ([image](https://goo.gl/photos/3DkkuGWr4cA2AVvD7))

Ow, found it (I'm using [Adguard](https://adguard.com/en/adguard-android/overview.html)).
Is there a workaround to use Adguard and Google login?

**Comment by s7092910** [comment]
I don't think we can. As I think adguard blocks webviews in apps.
