### ISSUE TITLE
Pokemons Search Crashing

### ISSUE THREAD

**Issue by mastescarhead1** [omkarmoghe/Pokemap#141]
Sorry if this is a bother,
But I see that on the main page, it no longer shows that pokemon display is yet to be merged
But on 6.0.1 I still see no pokemons. I'm wondering whether that's a bug?

**Comment by s7092910** [comment]
You need to long press the map where you want to search

**Comment by mastescarhead1** [comment]
It simply crashes when I do that...

**Comment by Kolyall** [comment]
Try to relogin, seems that now server PTC is not available

**Comment by mastescarhead1** [comment]
Tried that, along with reopening app. Crashes regardless of PTC or Google account. 
Someone reported the same findings in another thread I believe

**Comment by Kolyall** [comment]
So ...seems that this thread can be closed

**Comment by mastescarhead1** [comment]
Except that post was in a thread that had a completely different issue
That user probably should have create a new thread afaik
Source: https://github.com/omkarmoghe/Pokemap/issues/100

**Comment by Kolyall** [comment]
Seems we need to add check of " is PTC server work or not" to avoid the same issues like this

**Comment by mastescarhead1** [comment]
PTC server is login only no?
The pokemons are hosted on a different server, hence why Google accounts can play
Yet, regardless of Google account or PTC account login on Pokemap, searching will crash
I wonder whether it's related to https://github.com/omkarmoghe/Pokemap/issues/131
