### ISSUE TITLE
Searching fails at a distance

### ISSUE THREAD

**Issue by tdawg3000** [omkarmoghe/Pokemap#146]
First off thank you all for all the hardwork on this app its truly magnificent but id like to report that it works for me almost perfectly except when trying to search some areas a few miles from my location it fails to search saying the servers may be down however the search works fine around my location.

**Comment by hhagmans** [comment]
For me it (almost) never works with the current version. I got it working one time, the other times I got the error message above.
If I use the apk from about 2 days ago (without bigger search distance, new exception handling..) it works without problems. More specifically, revision ff52bb41a82e43675a3371be8a2eb62294599f74.
There is definetely an error in the latest code.
Edit: I've tested it in an emulator and it works. But it's not working on a Galaxy S6 or a LG G3. I'll see if I can find the problem...

**Comment by tdawg3000** [comment]
Im using the galaxy j3 and after more testing it seems to be a specific shopping center around my area it wont work in. And the 160 something revision worked in that area but now on 190 something with bigger search that area is not longer working. It is a very popular area so i think it might be because so many gamers already in that area

**Comment by mastescarhead1** [comment]
One of the coders misunderstood and thought that the crash was due to servers being down (which it wasn't). Pokemon spawn servers are independent of PTC servers.
Hence, whenever an error is thrown, it now shows that there's no connection or servers are down.
That needs to be fixed. The true error is that it crashes when too many pokemon are around

**Comment by hhagmans** [comment]
I've tested a few commits and commit a5a19b2105c6c6d3c76507e20bb097527417505e is the first one that doesn't work anymore. Before that everything works ok, then it starts crashing (or showing the error message in newer versions).

Edit: Ok I see, that makes sense, as the commit above is the commit that enlarges the search area.

**Comment by kyr0** [comment]
Hi, we are working on that. The issue will be addressed soon.

**Comment by comann** [comment]
The latest on dev should have this fixed. Thanks @LinkOut

**Comment by hhagmans** [comment]
Yep, works for me, thanks!

**Comment by tdawg3000** [comment]
Just got home from work going to test new rev now

**Comment by tdawg3000** [comment]
Just tried rev 224 and have to say that its working splendidly. The area i previously brought up as un-reachable now loads pokemon when i scan. Success! On another note the message at bottom that says how many catchable pokemon are around pops up after every pokemon spawns on map and when the scan finishes says theres 0 around when not the case

**Comment by tdawg3000** [comment]
Also timer seems to be working well now as well
