### ISSUE TITLE
not working at all..

### ISSUE THREAD

**Issue by roflinger** [omkarmoghe/Pokemap#152]
i start it and have a loading circle thats it... since the todays´ versions it´s not working anymore
lilipop xperia z

**Comment by mastescarhead1** [comment]
^ Just a spinning wheel of death!

**Comment by wjwolf79** [comment]
was getting this before the most recent version.  suggest trying to get the latest.

**Comment by mastescarhead1** [comment]
Anything later than r207 (haven't tested 205/203 yet) has this bug
r200 is fine

**Comment by roflinger** [comment]
thx, ill try!

**Comment by mastescarhead1** [comment]
r216 still no go

**Comment by wjwolf79** [comment]
right-o!  the latest code compiles and doesn't have the spinning wheel of death.  I guess it hasn't been auto-built yet

**Comment by jLynx** [comment]
@wjwolf79  Still there for me...

**Comment by wjwolf79** [comment]
well, that's just interesting.

**Comment by mastescarhead1** [comment]
r217 hasn't been released
r216 is what's available
I'm not sure if wjwolf79 is referencing 217, which the bot already ran and succeeded

**Comment by wjwolf79** [comment]
I'm smoking the good stuff... dummy me was using a different fork for my code base.  it works fine.. the master code doesn't work.

**Comment by mastescarhead1** [comment]
So that means we still gotta figure out what's wrong with r207+

**Comment by IsraelCabrera** [comment]
Hello, about this error, I only commented
showProgress(true);
in line 279 of LoginActivity.java
hope this helps

**Comment by wjwolf79** [comment]
yep.. that's it.  something in the showProgress method causes it

**Comment by s7092910** [comment]
I have found the issue and have fixed it.

**Comment by jLynx** [comment]
Should be solved in the latest build
