### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by roflinger** [omkarmoghe/Pokemap#153]
Curious, I am on v200 now and every time I look for pokemons near my location I get the error:

An internal error occured, This might happen when you are offline or the servers are down.

As soon as I scan 10 km away from my GPS spot it works without any problems.
On v.151 I did´nt have this issue.

**Comment by mastescarhead1** [comment]
Try r216 and see whether that works
Mind you, I have spinning wheel of death on it

**Comment by roflinger** [comment]
same for me, spinnng wheel

**Comment by jLynx** [comment]
I was in the middle of working on an update then on one of my tests I got the wheel....maybe its on Pokemon Go's side?

**Comment by mastescarhead1** [comment]
Servers are online tho. Including PTC servers
I dunno what else on their side would cause this.

**Comment by jLynx** [comment]
Its strange because the build was working, added a quick change which would not of affected this then when it tried to start up again I got the wheel. 

The other possibility is they have gone over the GMaps API key limit

**Comment by roflinger** [comment]
currently i got 165 installed, working perfectly

**Comment by mastescarhead1** [comment]
Pre-205 I think crashes when there are too many pokemon around

**Comment by jLynx** [comment]
@mastescarhead1 possible, will try check that now

**Comment by jLynx** [comment]
Should be solved in the latest build
