### ISSUE TITLE
Move login and network operations to a NetworkManager

### ISSUE THREAD

**Issue by omkarmoghe** [omkarmoghe/Pokemap#16]
Abstract the ugly ass nested http requests and redirect interception to manager that handles this and all other network calls

**Comment by comann** [comment]
Do you have any guidelines are using third party libraries such as Retrofit to help reduce the need for nested requests and all the overhead for http/https requests?

**Comment by FabianTerhorst** [comment]
I had an idea to simplify this logic. Is a pr welcome for this?

**Comment by omkarmoghe** [comment]
@FabianTerhorst Of course! I know that @VanshilShah is also working on a PR to clean up a lot of the network code. Definitely get in touch with him and you guys can coordinate!

**Comment by omkarmoghe** [comment]
fixed with #19
