### ISSUE TITLE
Password in setting not hidden

### ISSUE THREAD

**Issue by jLynx** [omkarmoghe/Pokemap#161]
The password in the settings is not hidden!

**Comment by fess89** [comment]
does it need to be hidden?

**Comment by jLynx** [comment]
Yes? Other wide I can't go into the setting with anyone around me as my password is visible

**Comment by s7092910** [comment]
We should actually remove the password and username from the settings activity since we have the login screen.

**Comment by jLynx** [comment]
I second this

**Comment by s7092910** [comment]
Ok I'll do it as part of my clean up of the login stuff.

**Comment by comann** [comment]
Fixed.
