### ISSUE TITLE
Can you please add a option of filtering pokemons .

### ISSUE THREAD

**Issue by tanishbaansal** [omkarmoghe/Pokemap#164]
Can you please add a option of filtering pokemons becuase i dont want any rattata or pidgey and a notification of pokemon would also be great.

**Comment by rohanjain1** [comment]
Notification of pokemon was literally added 2 mins ago :)
Filter options are WIP, stand by.

**Comment by tanishbaansal** [comment]
Okay thanks.. can you answer one more question ... Can i edit the code and then share the apk with my freinds ... i will give all the credit to the devloper and this page in the about tab

**Comment by damianstasik** [comment]
Why don't you create a pull request and share the apk from this repo?

**Comment by jLynx** [comment]
Already on the list to do #128

**Comment by tanishbaansal** [comment]
Okay ... but can i edit the apk?

**Comment by jLynx** [comment]
Yes the source code is here

**Comment by rohanjain1** [comment]
It's open source, so you can (edit the code and build an apk). Just make sure you understand the licensing requirements.

**Comment by tanishbaansal** [comment]
Can i share it on google play or any other android app sharing site ?

**Comment by rohanjain1** [comment]
Check licensing types and their meanings..

**Comment by tanishbaansal** [comment]
Okay .. thanks for replying bacj

**Comment by fess89** [comment]
check out #175
