### ISSUE TITLE
Can we use the source code and edit as our own ??

### ISSUE THREAD

**Issue by tanishbaansal** [omkarmoghe/Pokemap#165]
Can i edit the code and then share the apk with my freinds ... i will give all the credit to the devloper and this page in the about tab.

**Comment by ManojMadanmohan** [comment]
Check the licence file in the repository.

I think it should be absolutely fine though, as long as you don't use it for commercial purposes.

**Comment by tanishbaansal** [comment]
Okay ... so i can share it on diffrent sites

**Comment by s7092910** [comment]
For the license that we use, you can modify it, you can put it on sites. But if you modify it, you must make the code public. 

You can not use it for commercial purpose(charging people to use it or to make money with it) without the agreement of all the people who have contributed to the project.

**Comment by rohanjain1** [comment]
And we would recommend not sharing this around too much just yet for the following reasons:
- The code is still in dev phase
- When the #dev believes it's ready, we will share it appropriately on the correct channels and sites
- You are free to fork the repo and develop on it, if possible, contribute to the project
- We are still waiting to see how Niantic is going to respond. If this becomes too public we might force their hand.

**Comment by tanishbaansal** [comment]
Okay so i will wait and the.ln share it
