### ISSUE TITLE
Exception which is causing crashes .

### ISSUE THREAD

**Issue by srshkmr** [omkarmoghe/Pokemap#166]
Caused by org.greenrobot.eventbus.EventBusException

org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods (SubscriberMethodFinder.java:67)

org.greenrobot.eventbus.EventBus.register (EventBus.java:136)

LoginActivity.onResume (LoginActivity.java:336)

**Comment by s7092910** [comment]
Will be fixing this.

**Comment by srshkmr** [comment]
More on the Exception 

Fatal Exception: java.lang.RuntimeException
Unable to resume activity {views.LoginActivity}: org.greenrobot.eventbus.EventBusException: Subscriber class com.riffbuzz.pokemontracker.views.LoginActivity and its super classes have no public methods with the @Subscribe annotation

**Comment by fess89** [comment]
what's com.riffbuzz.pokemontracker.views.LoginActivity? I think the package name now is com.omkarmoghe.pokemap, and it does have an annotated method

**Comment by srshkmr** [comment]
I changed the package names to test with fabric .. this is a report from fabric

**Comment by s7092910** [comment]
@sureshvaavel have you made sure that it is up to date with our commits?

**Comment by srshkmr** [comment]
yes mine is latest

**Comment by srshkmr** [comment]
@s7092910 this doesnt happen anymore i fixed this :+1:
