### ISSUE TITLE
Automatically lock onto user's position and scan.

### ISSUE THREAD

**Issue by Giggitybyte** [omkarmoghe/Pokemap#167]
Small feature request.

Could you guys add an option in the settings to automatically lock onto the user's position and scan the area for Pokemon every X minutes? I feel that not only would this make it easier for the user, ~~but it would also enhance the new background service function by allowing users to see what Pokemon are in the area without the need to leave the Pokemon GO app.~~ whoop, didn't notice that the background service already did this. It will would be cool to have for the main map!

**Comment by CEBATOR** [comment]
You could also add to that notifications for specified pokemon.

**Comment by vidarr101** [comment]
Not sure what you mean but for me the background service/notification does grab fresh data from current location.

**Comment by Giggitybyte** [comment]
Does it? I wasn't too sure as I haven't had the chance to try it out. Still would be nice for the main map!
