### ISSUE TITLE
Pokemon icons are very large.

### ISSUE THREAD

**Issue by Giggitybyte** [omkarmoghe/Pokemap#168]
Pokemon icons are _very_ large. Could we get them down to the size of Pokestop icons?

<details> 
  <summary>

Click to see screenshot</summary>

    ![screenshot_2016-07-25-23-39-30](https://cloud.githubusercontent.com/assets/19187704/17128631/fbd2e99a-52c2-11e6-93e9-4b83030abe0a.png)
</details>

Using a Samsung Galaxy Core Prime SM-G360T1 running Android 5.1.1 with a DPI of 240.

**Comment by rohanjain1** [comment]
Oh jeez.. gotta get on this pronto

**Comment by s7092910** [comment]
We are currently testing the fix on PR #169. If it works, it will be merged.

**Comment by rohanjain1** [comment]
Resolved with latest commit.

**Comment by Giggitybyte** [comment]
Thanks guys!

**Comment by Giggitybyte** [comment]
@rohanjain1 @s7092910 @comann The issue has returned with [development build 297](https://github.com/omkarmoghe/Pokemap/releases/tag/dev-rev297). See screenshots below and please reopen.

<details> 
  <summary>

Click to see screenshots</summary>


<details> 
  <summary>

Build 297 (current build)</summary>


![screenshot_2016-07-26-15-08-08](https://cloud.githubusercontent.com/assets/19187704/17157386/c02703dc-5343-11e6-968f-514fb015f6df.png)
</details>
<details> 
  <summary>

Build 289 (previous build)</summary>


![screenshot_2016-07-26-15-12-58](https://cloud.githubusercontent.com/assets/19187704/17157392/c68bb718-5343-11e6-8a08-f54bfa43f32b.png)
</details>
</details>

**Comment by Giggitybyte** [comment]
Issue still persists in development build 309.
