### ISSUE TITLE
[Sugestion] Add a view to detarminate that "Searching is running"

### ISSUE THREAD

**Issue by Kolyall** [omkarmoghe/Pokemap#172]
Add a view to detarminate that "Searching is running"
![screenshot_2016-07-26-11-44-23](https://cloud.githubusercontent.com/assets/3495165/17135842/6ff2b7d4-533a-11e6-8706-d1d860ea2c5b.png)

**Comment by comann** [comment]
Fixed on Dev Tip. @kyr0 Thanks.
