### ISSUE TITLE
Pokemon icons blinking.

### ISSUE THREAD

**Issue by AEfremov** [omkarmoghe/Pokemap#173]
Hi all!

While searching for pokemons, icons of found pokemons blink but don't stay on the map.
Phone - LGE Nexus 5 6.0.1

**Comment by syfercv** [comment]
Comparing with the desktop version at the same time, i think the blinking ones are the expired pokemons being removed 

**(Edit)** After seeing a blinking pokemon on the map and going to the marked location I stilll caught it. So I was wrong on the expired theory

**Comment by AEfremov** [comment]
Maybe it's connected, but i can't say. In early versions all discovered pokemons were marked as "Expired" (even if it's not true). Clicking a pokemon marker on the map didn't lead to showing the remaining timer.

**Comment by josemariaaraujo** [comment]
Same here. 
I see a marker blink and if I go to the location I can capture it.  
When searching  I get a message like  "5 pokemon found" but only 4 are shown in the map. The 5th is the one that blinked.

**Comment by comann** [comment]
This is getting bumped to next release. Due to new information discovered about the blinking Pokemon.

**Comment by rohanjain1** [comment]
Resolved. Markers with negative timestamp caused this.
New feature implemented: user can see trnslucent image of a pokemon which will spawn in the near future. (no exact time yet.)
