### ISSUE TITLE
Dev chat?

### ISSUE THREAD

**Issue by jLynx** [omkarmoghe/Pokemap#177]
Is there any dev chat or IRC going on for this? I know there is Slack but I haven't got an invite yet to join...

**Comment by rohanjain1** [comment]
A pretty heavy slack going on for this, @omkarmoghe can see if we can open up the invitations again

**Comment by jLynx** [comment]
@rohanjain1 Would really like that invite as I have done a few commits here now and have no contact with any other devs here

**Comment by rohanjain1** [comment]
Am aware of that :) @omkarmoghe is managing the slack, so lemme check with him and see what we can do

**Comment by comann** [comment]
@DarkN3ss61 you should be receiving one soon.
