### ISSUE TITLE
Possible bug: Google authorisation switch off.

### ISSUE THREAD

**Issue by goodjumpsun** [omkarmoghe/Pokemap#179]
Android 5.1

Setup -> Google login -> working OK
Shut down app -> not working and no any place to enter and save Google login info. 

Reinstall app -> Google login -> working OK

Thank you.

**Comment by thisismohitgupta** [comment]
I too have these same Issues from the morning . Please help me out

**Comment by thisismohitgupta** [comment]
when I use the default client secrets the app works fine.But when I try to change them 

 mPokemonGo = new PokemonGo(mAuthInfo, mPoGoClient);

this line on NianticManager.Java throws a big error

**Comment by omkarmoghe** [comment]
We strongly recommend you use a PTC account and not google. We haven't tested GAuth extensively and there is a chance you could get banned for GPS spoofing.

**Comment by thisismohitgupta** [comment]
this is the error 

Setting google auth token failed. setGoogleAuthToken() raised: null

**Comment by thisismohitgupta** [comment]
any Idea
