### ISSUE TITLE
Add Support for using local Google Accounts (OAUTH)

### ISSUE THREAD

**Issue by comann** [omkarmoghe/Pokemap#18]
Currently, it appears this app only support Pokemon Trainer accounts.
If possible, add support to use the local gmail accounts that the user has already provided to android system, and provide them as an oauth credentials

**Comment by omkarmoghe** [comment]
Yes, for sure. Waiting on the network stuff to be cleaned up and moved to a different file, then we can start adding other auth methods.

**Comment by s7092910** [comment]
@omkarmoghe I could handle this. Was planning on doing this anyway by doing a login screen and changing a bit of the function of the preferences.

**Comment by omkarmoghe** [comment]
@s7092910 cool! Yeah we def need a login screen. Some of the shared prefs have already been added. Just make sure you guys stay even with `master` so that you are building off existing work and not reinventing stuff or duplicating efforts :smile:

**Comment by s7092910** [comment]
So it might not be possible to do a google login by doing a one click google sign in. Without this, I suggest we don't add a google sign in. I do have one more option that I can try. If it doesn't work, the one click google sign in won't work.

**Comment by sidhantpanda** [comment]
I doubt one-click google sign in (through OAuth) will work as we still need the password which needs to be given to the Niantic API. We can't authenticate on behalf of Niantic

**Comment by s7092910** [comment]
With google login, the Niantic API doesn't need the password. It only requires a Google Sign In Server Token. Getting that is not exactly easy on a phone in the app without using a web browser.

**Comment by sidhantpanda** [comment]
How were we doing it via command line without a browser with the original project? I am a little confused about the auth process now

**Comment by Ramiloom** [comment]
@sidhantpanda it the command line tool the user had to write his own google account and password.
Ninatic using the one-click google sign (OAuth) which uses a token that was signed by the Google Sign In Server.

Long story short, we need the users password to use the old command line method.
If we want to use OAuth, we need to add a new method to sign in.

**Comment by sidhantpanda** [comment]
But can we pass the token generated by us (without using Niantic's client id and client secret) to Niantic?

**Comment by sidhantpanda** [comment]
Anyway, OAuth is pretty straight-forward. I can integrate this into the app easily. We need to create a Google Project, get our keys and service files. I recommend @omkarmoghe to be the owner for this.

**Comment by s7092910** [comment]
@sidhantpanda and @sidhantpanda The command line tool is a bit more complicated. What it is doing is login the person into a device, gets some sort of code from said device and then used that code to do a auth with the google servers with Niantic's OAuth details. Which then returns the Token for that account for Niantic's server.

That Token is what determine's who's google account is tied to that pokemon go account.

Because of all of that, we can not pass a token generated by us unless we want it to create a new account or possibly collide with another account on the pokemon go server (highly unlikely but possible). Which with what we are doing is against the TOS, we can't have it go to another person's account.

Also for security reasons, we shouldn't be doing it with having access to the person's google account, on top of that it requires 2FA to be turned off if we do it the same was as the command line. I'm all for having a google sign in, but not at the cost of someone's security to their google account.

**Comment by sidhantpanda** [comment]
@s7092910 Ah ok!

**Comment by s7092910** [comment]
@sidhantpanda So I might have been a little bit stupid last night, it was late. What code seems to be is an OAuth Token that can be used to access certain features of a user's google account. It probably is the google account that determines which pokemon go account it is.

So I got most of it done, the only issue I have right now is when I send that token to the pokemongo servers I get a error=invalid_grant

**Comment by s7092910** [comment]
So I have completed doing the google login, it isn't a normal google login for an app, but it works. Currently working on fixing the PTC login and then going to create a Pull Request for it.

**Comment by comann** [comment]
So the pokegoapi utilizes google oauth.....but it is not easy to use for a user......

**Usage**
```
 mAuthInfo = new GoogleLogin(client).login(username, password);
```


However beneath the hood there is code that looks like this:
```java
            //Make the call
            Response response = this.client.newCall(request).execute();
            GoogleAuthJson googleAuth = (GoogleAuthJson)gson.fromJson(response.body().string(), GoogleAuthJson.class);
//This indicates the user must get to this url and enter the code given back from Google as a verification. This is a onetime mandatory thing....I have tested and it indeed works
            Log.d(TAG, "Get user to go to:" + googleAuth.getVerificationUrl() + " and enter code:" + googleAuth.getUserCode());

            // Block the entire thread until the user performs said task....
            GoogleAuthTokenJson token;
            while((token = this.poll(googleAuth)) == null) {
                Thread.sleep((long)(googleAuth.getInterval() * 1000));
            }

            Log.d(TAG, "Got token: " + token.getIdToken());
            ```

**Comment by s7092910** [comment]
Yeah I already got it working, it works I believe the same way as the PokeGOAPI.
