### ISSUE TITLE
Search bugs out post-minimize

### ISSUE THREAD

**Issue by mastescarhead1** [omkarmoghe/Pokemap#197]
If the app is minimized, then brought back to mainframe, the search region notifier works (white target), but the blue circles only center on where you currently are
No searching actually occurs

**Comment by quinnj** [comment]
I believe this is the issue I'm seeing as well, as of this morning on the `dev` branch.

**Comment by cwizard** [comment]
Closed my issue to comment here, this behavior seems to persist after any focus is taken away from the app at all.

**Comment by hybridtracer** [comment]
I had opened same one...closed it to consolidate. Can a dev please reply here when this is looked at, because its almost unusable when you can't take focus off.

**Comment by omkarmoghe** [comment]
hey thanks for bringing this up guys, this is definitely a high priority for us.

**Comment by comann** [comment]
This is been fixed on dev tips.

https://github.com/omkarmoghe/Pokemap/commit/950a66dfa9ca67c0a79030b09c1a06cf7067d67f

**Comment by hybridtracer** [comment]
Still happens on revision 386 for me.
