### ISSUE TITLE
Continuous count down timer

### ISSUE THREAD

**Issue by GiantForkLift** [omkarmoghe/Pokemap#198]
Have the timer for each Pokémon continually count down rather than having to search again to have it go down.

Great work on the app by the way!

**Comment by comann** [comment]
Include also a countdown for lures.

**Comment by Giggitybyte** [comment]
@comann @rohanjain1 Hasn't this recently been implemented?

**Comment by comann** [comment]
I think so but @rohanjain1  would know. He was the one doing the majority of this work.

**Comment by s7092910** [comment]
Yes it was implemented and updated last night. So it should be in the latest dev build.
