### ISSUE TITLE
Setup Travis CI for APK builds

### ISSUE THREAD

**Issue by JakeCooper** [omkarmoghe/Pokemap#2]
APKs can be built using Travis when users merge pull requests.

https://docs.travis-ci.com/user/languages/android

**Comment by Jawnnypoo** [comment]
So this one can be closed probably, you will just need to enable travis at travis-ci.org

**Comment by omkarmoghe** [comment]
Yep enabled!

**Comment by apaatsio** [comment]
Can you provide instructions how I can download APKs from travis? I couldn't find any successful builds or downloadable files.
