### ISSUE TITLE
Initial Search Does Not Work

### ISSUE THREAD

**Issue by andycervantes** [omkarmoghe/Pokemap#201]
Initial start of program does not allow for searching of Pokemon to work. Placing marker anywhere in the map will return with "0 Pokemon found". Clicking on the settings option on the top right and returning back to the map seems to "fix" the search issue.

I only ran into this issue after installing the newest apk. Restarting the same apk does not have the searching issue from above.

**Comment by dmcdaniel12** [comment]
Can confirm. Also having this same issue.

**Comment by strobil** [comment]
Confirm, have the same issue. Sometimes full app restart helps.
