### ISSUE TITLE
Can I increase the search range ?

### ISSUE THREAD

**Issue by juanpedroo** [omkarmoghe/Pokemap#206]
How can i increase the search range of pokemon in java classes ?

**Comment by socrates2510** [comment]
SearchParams (but don't PR that change)

DEFAULT_RADIUS \* 3  (3 is the steps, concentric hex, to search).

**Comment by Gondost** [comment]
Modifying it doesn't appear to have an effect, at least not to my eye.  The highlighted circle expands but the concentric hexes appear to stay at 3 regardless of what the DEFAULT_RADIUS \* n is set to (tested 4, 5).

**Comment by juanpedroo** [comment]
ok thank you
