### ISSUE TITLE
Map loads, pokemon does not

### ISSUE THREAD

**Issue by Jasondhillon** [omkarmoghe/Pokemap#21]
I have a working login put into the token section, and I un-commented the getPokemon function, but still no pokemon are appearing on the map. Not sure where to go from here.

**Comment by s7092910** [comment]
It is because we haven't exactly put that together yet.

**Comment by Jasondhillon** [comment]
ahh that explains EVERYTHING. Thanks and goodluck!

**Comment by omkarmoghe** [comment]
thanks!
