### ISSUE TITLE
Pokemon icons too large/not normalized

### ISSUE THREAD

**Issue by rbryson74** [omkarmoghe/Pokemap#212]
It looks like one of the releases today (July 26) changed the appearance of the icons on the map. Most are now too large and it looks like some pokemon are much larger than others. For example, Paras and Pidgey are quite large and Eevee are much smaller.

**Comment by Giggitybyte** [comment]
See #168

**Comment by rbryson74** [comment]
Well that's odd. I only started seeing this after about halfway through the releases today. It seemed ok this morning.

**Comment by rbryson74** [comment]
I see your new comment on #168. Thanks Giggitybyte

**Comment by rbryson74** [comment]
I was looking through the code. There are a huge number of changes regarding the new remoteimageloader. Personally I'd rather have the icons in the local cache instead of reloading over the network every time.

**Comment by Giggitybyte** [comment]
Woah. After a quick uninstall and reinstall, I just got the bug you originally described. Icons are of varying sizes. 

<details>
<summary>

Click to see screenshots</summary>


![screenshot_2016-07-26-16-36-17](https://cloud.githubusercontent.com/assets/19187704/17159080/77efc444-534f-11e6-989e-d692be0b7acf.png)

<h2>Edit: more screenshots.</h2>

![screenshot_2016-07-26-16-52-26](https://cloud.githubusercontent.com/assets/19187704/17159539/d683ce9e-5352-11e6-8956-8abf4d8b86b0.png)
![screenshot_2016-07-26-17-01-30](https://cloud.githubusercontent.com/assets/19187704/17159541/da04ec2e-5352-11e6-9e23-db66c03b266a.png)
![screenshot_2016-07-26-17-01-53](https://cloud.githubusercontent.com/assets/19187704/17159544/dd69b34a-5352-11e6-8bff-ee8dab49fcaf.png)

</details>

**Comment by Giggitybyte** [comment]
Seems to be persistent in development build 309.

**Comment by comann** [comment]
What phone are you running the app on?

**Comment by rbryson74** [comment]
Giggitybyte is running a Samsung Galaxy Core Prime SM-G360T1 and I am on a Samsung Galaxy Tab A 8

**Comment by rbryson74** [comment]
In the app/src/main/res/values/dimens.xml There are two new lines:

```
<dimen name="pokemon_to_show_icon_size">48dip</dimen>
<dimen name="pokemon_to_show_icon_margin_left">8dip</dimen>
```

All the other items in the file have values as "dp" instead of "dip". Will this make a difference anywhere? My Java/xml is pretty rusty.

**Comment by omkarmoghe** [comment]
`dip` and `dp` [should be the same](http://stackoverflow.com/a/2025541/5734895), but the [android docs](https://developer.android.com/guide/topics/resources/more-resources.html#Dimension) dont seem to have `dip` anywhere.

**Comment by rbryson74** [comment]
I did find some documentation on dip. it is essentially the same as dp. It just refers to the "density Independent Pixels". the doc I read says dp is preferred to stay similar to "sp" which is the scale independent pixels. I think it won't make a difference in this case. 

As I said my coding is rusty. I was only able to trace down to where the icons are set. At that point I am not sure what needs to be done next. Sorry. :(

**Comment by rbryson74** [comment]
Those two lines I mentioned above are just for the icons in the filter list in the settings menu. I think I will go do something else now.

**Comment by s7092910** [comment]
@rbryson74 does this happen on the latest dev branch?

**Comment by rbryson74** [comment]
I just checked dev-rev394. The icons appear much better now. Thank you.

**Comment by rbryson74** [comment]
They were ok until I took some out of the filter list. Some of them are the correct size but others were much larger than they should have been. Especially the catterpee and Voltorb I could see.

**Comment by Giggitybyte** [comment]
Yeah, I was going to comment here when I got home. Something is going funky with the filter list. Everything is fine until I open that up and scroll through it. After a scan or two the icons get all funky.

I'll record a video of it when I'm home.

**Comment by s7092910** [comment]
Thanks for the info. I finally was able to reproduce it and I know exactly what is going on. It should hopefully be fixed tonight

**Comment by rbryson74** [comment]
Thanks s7092910, I'll be very interested to see what it was in the code.
