### ISSUE TITLE
Add Chat head like button & System Overlay of Main Activity

### ISSUE THREAD

**Issue by sakakun** [omkarmoghe/Pokemap#220]
I've scene with "Go Messenger" that they've implemented a chat head that opens there main activity as a system overlay so you may open it without having to leave the Pokemon Go app.

Could this be implemented with this as well?

**Comment by Giggitybyte** [comment]
See [here](https://github.com/omkarmoghe/Pokemap/issues/176#issuecomment-235240406).

**Comment by axsddlr** [comment]
that would kill your battery so quickly
