### ISSUE TITLE
[Bug] Pokemons Filer Adapter is blinking

### ISSUE THREAD

**Issue by Kolyall** [omkarmoghe/Pokemap#229]
- run the app
- go to settings
- go to "pokemon to show"
- scroll down

[bug] 
 Adapter is blinking
[Video](https://www.dropbox.com/s/ogkltdzhw1fye77/mobizen_20160727_110703.mp4?dl=1)

**Comment by LinkOut** [comment]
Thats due to Adapter of that list, thank you for reporting. 
Will fix it.

**Comment by chrosey** [comment]
got that too, but when all images got loaded it's gone

**Comment by fess89** [comment]
why did we remove the pokemon drawables in the first place? do we expect them to change often?

**Comment by Kolyall** [comment]
@fess89 maybe we can add a placeholder to display a default image while real image is loading?

**Comment by fess89** [comment]
@Kolyall for sure we can, I think Glide has to have such an option

**Comment by LinkOut** [comment]
@fess89 Yep, Just add .placeholder(R.drawable.your_holder)

Also error: .error(R.drawable.your_error_image), when there's some error loading images

**Comment by fess89** [comment]
@LinkOut not that easy, because RemoteImageLoader is used:

`RemoteImageLoader.load(
                    "http://serebii.net/pokemongo/pokemon/" + PokemonIdUtils.getCorrectPokemonImageId(pokemonId.getNumber()) + ".png",
                    64, 64,
                    row.getContext(),
                    new RemoteImageLoader.Callback() {
                        @Override
                        public void onFetch(Bitmap bitmap) {
                            mImageView.setImageBitmap(bitmap);
                        }
                    }
            );`

I will give it an extra placeholder parameter after my last PR gets merged so I don't mess it up

**Comment by jLynx** [comment]
Please re-open the issues if this is not fixed in the current release
