### ISSUE TITLE
Slack or IRC channel for collaboration?

### ISSUE THREAD

**Issue by sidhantpanda** [omkarmoghe/Pokemap#23]

**Comment by Mahonster** [comment]
I'd personally be happy with any channel for communication!

I'm trying to get involved with this project but I'm more of a front end "make things look pretty" dev. Slowly reading through the original project and this framework trying to understand.

Anything would be great :)

**Comment by CanOrhan** [comment]
The website indicates that there's a Discord channel for the main app. Perhaps a room in that for devs could be good?

**Comment by fess89** [comment]
Strangely, I have never heard of Discord before. Is it worth using?
For me, Slack would be the best option.

**Comment by CanOrhan** [comment]
It's pretty good. Multiplatform with a web client so you don't need to download it. To be honest, I'd prefer a slack channel with integrations. That'd be awesome

**Comment by fess89** [comment]
I've created a channel, feel free to join:
https://pokemap-android.slack.com

**Comment by omkarmoghe** [comment]
the main repo's discord channel has an #android channel. that might be easier since all the other devs are in the discord as well.

slack works too

**Comment by CanOrhan** [comment]
@fess89 I think I need an invite. Could you send one to `can [AT] kiwisoft [DOT] co [DOT] uk` please?

**Comment by fess89** [comment]
@CanOrhan sent an invite, check it out. I wonder how to make it public for everyone.

**Comment by jmrapp1** [comment]
Can you add `jmrapp1270 [AT] gmail [DOT] com` as well? Im pretty sure there is a setting for the team that you can switch on and off to make it invite only or public.

**Comment by sidhantpanda** [comment]
Can you please add sidhantpanda@gmail.com too?

On Thu, Jul 21, 2016 at 6:41 PM, Jon R notifications@github.com wrote:
Can you add jmrapp1270 [AT] gmail [DOT] com as well?

**Comment by omkarmoghe** [comment]
@fess89 can you try to make the link public? I can add it to the readme!

**Comment by fess89** [comment]
@sidhantpanda @jmrapp1 added you. The link is here:
https://pokemap-android.slack.com/signup

**Comment by jmrapp1** [comment]
Did not receive an invitation email. When I try to sign up it requests a `github.io` email which I don't have. Why am I not able to use just a standard email? I've never used Slack before.

**Comment by fess89** [comment]
Turns out that you cannot make a team truly "public" on Slack. The only option is to allow signup for people with emails in a specific domain, and gmail.com cannot be used as that domain, so I used github.io. Anyway, just tell me your email address and I will add you.

**Comment by omkarmoghe** [comment]
theomkarmoghe@gmail.com 👍
