### ISSUE TITLE
Feature Request: mark Pokemon as "catched"

### ISSUE THREAD

**Issue by Nicolai0685** [omkarmoghe/Pokemap#232]
It would be nice if you could remove a single Pokemon from the Map if you already catched it in Pokemon Go

**Comment by LinkOut** [comment]
That's not possibile, since Pokemap and PokemonGo uses 2 different accounts. All pokemons are visibile to all. Pokemap does not catch it, otherwise it will disappear.

**Comment by s7092910** [comment]
What @LinkOut has said is true. But it might be possible for us to add a feature to allow the user to remove a pokemon from the map.

**Comment by Nicolai0685** [comment]
@ s7092910: thats what i meant. just remove it from the map. (and notifications)

**Comment by LinkOut** [comment]
@MrUnknown85 YOU (as user) will be able to remove it manually, no other magics will happen :P. I mean you have to remove it (by hand) from Pokemap when you catch it on official app.

**Comment by Nicolai0685** [comment]
my idea was:
- when you get the available pokemons nearby: get the pokemonId from the pokemon.
- add an option to the map (maybe beneath the expired-counter: 'catched it'
- when you click on it: pokemon with that pokemonId gets removed from the map and from notifications. pokemonId is stored (maybe in sharedPreferences).
- next time you get available pokemons: check for all pokemons if the pokemonId is stored in prefs.
  if thats the case: dont display it on the map.
- when pokemon expires: remove pokemonid from prefs.

**Comment by visualfanatic** [comment]
You could just uncheck it in the filter list. One thing that could be done would be to add a button which would show up after tapping on Pokemon, that button would toggle that Pokemon on the list.

**Comment by Nicolai0685** [comment]
when i uncheck it in the filter list, then no pokemon at all of that kind will be displayed anymore. thats not what i want.

**Comment by Giggitybyte** [comment]
I understand what you're thinking of, and I personally think this is a great idea.

**Comment by Nicolai0685** [comment]
the thing is: when i catch all Pokemon nearby with my real account, they still appear in Pokemap because its a different account. so i have to ask myself all the time: is this a Pokemon i already catched in Pokemon Go, or is it a new one??

understand what i mean?

**Comment by Giggitybyte** [comment]
Yes yes. I understood from the start. Not sure why some others didn't understand.

**Comment by Giggitybyte** [comment]
I am just wondering how it would be implemented for the end user. Would there be an option in the little pop-up that comes up when you select a Pokémon? Or perhaps a long press to remove sort of thing? Maybe a 'remove' mode for removing/marking several at once?

**Comment by Nicolai0685** [comment]
'remove mode' sounds pretty good.

**Comment by Nicolai0685** [comment]
you just have to be careful then, if pokemon are close together, so you dont accidently click and remove the wrong pokemon. or add an "undo" option in the snackbar

**Comment by Kolyall** [comment]
Can we connect two accounts(fake and real) to the Pokemap? Then we can verify which of pokemon was catch last time in real account and remove it from the map.
Or Pokemon Go servers doesn't allow connection in two applications? Can servers determinate that we are in two different applications?

But this way will take a lot of time implementation.

**Comment by Nicolai0685** [comment]
@Kolyall
Using this software is against the ToS and can get you banned. Use at your own risk.

not the best idea connecting accounts.

**Comment by PetrGasparik** [comment]
I support this idea, 
plus, I enhanced it with "remove only from notification"

As there are Pokémon that are desired to be shown on map, but one does not necessary need to be notified about. 

see https://github.com/omkarmoghe/Pokemap/issues/239

**Comment by Nicolai0685** [comment]
i have implemented this feature. can i push it?

**Comment by jLynx** [comment]
Please re-open the issues if this is not fixed in the current release
