### ISSUE TITLE
Italian Translation

### ISSUE THREAD

**Issue by ghost** [omkarmoghe/Pokemap#236]
Hi,I'd like to create a Italian Translation of this app.
That's userful?
How can I create it?

**Comment by Kolyall** [comment]
-just make "fork"
-make changes
-then make pull request

**Comment by omkarmoghe** [comment]
@mpcom00 yeah definitely. as @Kolyall said: fork the repo and PR the changes.

**Comment by omkarmoghe** [comment]
fixed with #253
