### ISSUE TITLE
Notification Bugs

### ISSUE THREAD

**Issue by Nicolai0685** [omkarmoghe/Pokemap#237]
1. notifications show negative expire time: WEEDLE(-24493591 minuten,26.0 Meter)
2. name of the pokemon is not translate into German (see above)
   3 (rather a feature): click on notification does not open pokemap

**Comment by chrosey** [comment]
I'm currently working on correct pokemonName. forgot to... pushing in few seconds #234

**Comment by chrosey** [comment]
maybe 1. can be fixed by using `getExpirationBreakdown(long millis)` from MapWrapperFragment,java?

did not have chance to see this happen...

**Comment by vidarr101** [comment]
Do we know if the time is wrong , or it just showing up even though its expired.  Could just do a >= 0 check :-).

**Comment by Nicolai0685** [comment]
i have a paras nearby. the notification shows -24494832 minutes. when i open the app, and click on the pokemon (its the only visible pokemon) then only the name is displayed. not the timer.
