### ISSUE TITLE
[Suggestion] Menu of desired actions for long press on Pokemon label

### ISSUE THREAD

**Issue by Gondost** [omkarmoghe/Pokemap#243]
I saw another suggestion for something to be added to a long press on the Pokemon label.  I think it was a good suggestion, but I think it's best not to limit it to 1 action.
- Mark Pokemon on map as "caught" (#232)
- Generate lat/lon map coordinates for driving or walking directions (while it's nice to see it on the map, it's helpful to be able to send the coordinates to Maps or Waze so I can navigate there while keeping PoGo in foreground.
- Other contextually appropriate long press actions

**Comment by CarstenHouweling** [comment]
Note on point 2: Why not integrate walking directions on the map itself? I only need a Server API key (created in the Google API Console) to implement this myself, but if anyone else wants to do this take a look at: https://github.com/akexorcist/Android-GoogleDirectionLibrary

**Comment by socrates2510** [comment]
I like that one (map directions). Only problem would be that we need people to add their own keys, since otherwise the free quota will be gone fast. Python team had that problem. 

I noticed directions become important when you are in a car

**Comment by Gondost** [comment]
API key should be easy enough to add as a text entry field in Settings.  Then the app would validate whether it's blank or not if someone tried to get directions.  A warning would probably be a good idea as well to not use your API key from the same Google account that holds your Go data, just in case.

Basically a long press menu is probably needed regardless even if only as a placeholder for future content.

(I'm not an Android developer, VB is the extent of my knowledge, so this is beyond what I'm capable of doing or I'd pitch in)

**Comment by socrates2510** [comment]
No warning needed as navigation occurs outside of pokémon go servers.

**Comment by CarstenHouweling** [comment]
I'll create a Directions part in settings and look into a custom Info Window that show's directions icons when an API key is provided.

**Comment by Gondost** [comment]
Should be the relevant info for a Geo intent:

https://developer.android.com/guide/components/intents-common.html#Maps

**Comment by CarstenHouweling** [comment]
@Gondost I don't see the relevance there... You want to open the Google Maps app or something?

**Comment by Gondost** [comment]
@CarstenHouweling No offense meant here, this is a legitimate question, do you actually play the game as well? 

If a user is staring at Pokemap to determine how to get to a nearby Pokemon, 1) it's inefficient, 2) it's unsafe while driving, 3) eggs won't hatch with the game closed, 4) with game closed you can't catch other Pokemon while in transit, 5) ??? 6) other things.

**Comment by CarstenHouweling** [comment]
@Gondost no no, I'm sorry if i came across as rude. I just didn't understand what the intentions were with opening a different app when we can implement directions in the same app (Pokemap). You do make a very valid point though: it is unsafe while driving.

What i usually do is quick toggle between apps (Pokemon Go & Pokemap) to see where i should go. Having a line in Pokemap for my walking route will be good for me.

Starting Google Maps directions in the background also sounds like a great option. Do you have an idea to start a background maps directions service in Android?

**Comment by Gondost** [comment]
No worries I figured you were just looking for clarification.

A walking line in-app could be beneficial for pedestrian traffic, for sure.  I'm not familiar enough with Android development to know _how_ it should be done, but the way PokeNotify did it was using the Geo intent as follows:
`"geo:0,0?q=34.99,-106.61(Treasure)"`
In Android, this pulled up the menu that lets you choose which of your apps that handles Geo coordinates should receive the data.  In my case since I use Maps and Waze and don't have a default set for that reason, I choose Maps, which then brings up their standard dialogue on walking, public transit, driving, etc, along with a marker and a label for the Pokemon.
