### ISSUE TITLE
Reducing background traffic

### ISSUE THREAD

**Issue by chrosey** [omkarmoghe/Pokemap#246]
got a quick view into my traffic.... nearly 900mb since monday.
somebody else experiencing alike?

**Comment by roflinger** [comment]
do you have the google maps offline available? give it a try

**Comment by omkarmoghe** [comment]
@chrosey thanks for bringing this up. we are checking out the network usage rn. i suspect most of the data usage comes from the images, but we are caching them so that should help. we will investigate further

**Comment by andycervantes** [comment]
I have done some testing and it seems that its coming from the background service used for searching/notifying found Pokemon.

**Comment by omkarmoghe** [comment]
@andycervantes yeah makes sense

**Comment by tdawg3000** [comment]
I downloaded google maps for my area threw google maps. Will the app automatically use the offline area if im inside it?

**Comment by chrosey** [comment]
i tested with an w/o offline maps by now. there's no difference between traffic.

i also have to state that its just the background traffic thats very high.

**Comment by vidarr101** [comment]
Are you talking about the background status notification.  If so, you can tweak the refresh rate in settings to make it update less or turn the whole thing off in general.

**Comment by chrosey** [comment]
sure I could do. but running refresh ever 20 sec would be slower than pokemon go (sth between 5 - 10 sec, if i see right) and this is not getting that much traffic

What I mean is, there should be another possibility to reduce this.

**Comment by Giggitybyte** [comment]
I remember seeing some constant network activity from the app before the background service was introduced.

**Comment by vidarr101** [comment]
I will take a look and see if I can trim some fat somewhere
