### ISSUE TITLE
Put the changes on each revision

### ISSUE THREAD

**Issue by Xelwon** [omkarmoghe/Pokemap#247]
Please. Can you put what are the changes on each revision on commit comments?
For example, minor internal changes, fixed search button, added new filter option, etc.

I will very glad. So I could know if I must reinstal the app or wait to another revision. 

Thank to you. Very good work

**Comment by comann** [comment]
Currently, we are still pre-release. Friday will be the first release of 0.1 and we will be versioning from that point on.
