### ISSUE TITLE
Failed to login

### ISSUE THREAD

**Issue by GiantForkLift** [omkarmoghe/Pokemap#248]
This may just be my phone/account but I am unable to login. Everytime I attempt to do so it tries to work but then takes me back to the login screen and says "Failed to login". I do know that my username and password are correct.

Build 321 worked for me last night, but failed to work this morning. I've tried the other latest builds as well and still no dice.

**Comment by Gondost** [comment]
Pokemon Trainer Club servers.

**Comment by GiantForkLift** [comment]
That would make sense. Hopefully it's just that. Thanks for the help!

**Comment by chrosey** [comment]
jup... 
see here: http://ispokemongodownornot.com/
