### ISSUE TITLE
[Bug] Update Loop

### ISSUE THREAD

**Issue by hybridtracer** [omkarmoghe/Pokemap#251]
I built Pokemap-dev-rev362 and when you first open the app it is fine and you can search anywhere. When it runs in the background and notifies you of nearby pokemon, it seems to go into a refresh loop at your location. It refreshes search nonstop at your current location and you can't search anywhere else.

I don't know if this is the right place to post or if you even care for these minute builds.

**Comment by chrosey** [comment]
#197 has the same issue, but not mentioning active notification service

**Comment by hybridtracer** [comment]
Hmm the notification service might not be causing the issue. It could be just minimizing and reopening like mentioned in #197. I just noticed because I was reopening due to notification.
