### ISSUE TITLE
PTC login failed on the latest build

### ISSUE THREAD

**Issue by sheikhsabayyal** [omkarmoghe/Pokemap#258]
JUST INTALLED THE LATEST build and it won't let me login with PTC account. The information is correct though. Anyone else facing this issue?

**Comment by hybridtracer** [comment]
PTC has been spotty for a few hours now. I don't think it is the apps fault.

http://ispokemongodownornot.com/

**Comment by sheikhsabayyal** [comment]
Seems okay in the link plus using it on the script on my mac. Just stopped from there to there to login here on the app and it didn't work.

Anyways I'll try again later to and update here accordingly

**Comment by s7092910** [comment]
The main thing we are looking for, for this is the logcat output for the app from the start till you get the failed login.

**Comment by Kensed** [comment]
It is working from desktop, but not from app.

**Comment by Ric87** [comment]
Hi guys,

hi tried to download the apk to my android device but it seems to fail to access to both Google and PTC account. Servers do not seem to have any problem as I can connect to the app.

Do you know how to fix this problem?

Thanks!
