### ISSUE TITLE
Search is not working on first time launch after install

### ISSUE THREAD

**Issue by almasmaris** [omkarmoghe/Pokemap#262]
Place marker anywhere in the map will return with "0 pokemon found".  App will showing pokemon after clicking "Pokemon to show" in setting.  

This issue happen on first time launch after installing the app.The application works fine after that.

**Comment by omkarmoghe** [comment]
This is probably because the default prefs for pokemon to show is most likely an empty list. Thanks for the catch we'll fix this!

**Comment by comann** [comment]
Check the latest on dev tip. Fixed.
