### ISSUE TITLE
New pokestop icons hard to see.

### ISSUE THREAD

**Issue by syfercv** [omkarmoghe/Pokemap#263]
Is it just me or are the new pokéstop icons very hard to see. The blue is too similar with the search area circule if it's on.  The old red ball was better .

And do you have plans of including satellite view in the map?

**Comment by Colbey** [comment]
I agree with this. I think overall, all annotations could use a normalized bubble / border (pokeball? heh) to help distinguish them from the map. this of course requires a lot of editing of images or a custom marker built for every object with the current image depending on where that image comes from.

**Comment by Sn3akySl0th** [comment]
I kinda agree with this one. I liked the little red ball as it didn't take up allot of the map. Especially in areas where Pokestops are heavily concentrated.

**Comment by jLynx** [comment]
I personally like what they are currently set to

**Comment by Giggitybyte** [comment]
The new icon is alright. I'd personally prefer the old Pokeball icon. My main gripe with the new one is that the bottom part of the icon isn't placed on the spot where the Pokestop actually is, like a Google Maps pin would. Right now, it's hard to tell exactly where it is without zooming in all the way.

I'd be happy with a revert to the old icon, or a fix for the current one.

**Comment by comann** [comment]
I'm a fan of the current one.

**Comment by socrates2510** [comment]
I like the current one. But scanned circle needs a new color to avoid distractions. I'll go with a yellowy one or greeny one.

**Comment by Colbey** [comment]
i agree with @socrates2510 on this one, but i feel that would be a separate issue/bug to track. I have added #288 for reference of that issue.
