### ISSUE TITLE
Gym not showing up on map

### ISSUE THREAD

**Issue by heomap14** [omkarmoghe/Pokemap#267]
Pokestop shows up perfectly but gym did not show up after enabled

**Comment by chrosey** [comment]
can you tell some steps to reproduce this? gyms work fine for me on latest build

**Comment by heomap14** [comment]
i log in, enable gym, and that's it.  Didn't really change anything.  But gym not showing up at all.
Relog, reinstall app did not fix.
I log in with Google acc.

**Comment by heomap14** [comment]
ok nevermind, restart the phone did the trick.. wonder why>
