### ISSUE TITLE
Organisation

### ISSUE THREAD

**Issue by CanOrhan** [omkarmoghe/Pokemap#27]
Hi folks! I'd really like to get involved with this project. Could I ask who I should be talking to regarding new features / changes?

**Comment by fess89** [comment]
Good question @CanOrhan, I would also like to contribute

**Comment by omkarmoghe** [comment]
Hey @CanOrhan and @fess89! I'm the owner of the Android port so you can always talk to me. The discord channel has a #android channel where we can discuss stuff or we can use @fess89 's slack channel. Either work for me

**Comment by CanOrhan** [comment]
@omkarmoghe Cool! I'm inclined to use slack since I've always got it on anyway. As I've mentioned before, it'd be good to get integrations for it too.

**Comment by LinkOut** [comment]
I would also like to contribute :)

**Comment by omkarmoghe** [comment]
@CanOrhan @LinkOut works for me. Ill add the link to the readme

**Comment by LinkOut** [comment]
Could you link the slack channel please

**Comment by omkarmoghe** [comment]
@LinkOut will do . what is your email? we can send you an invite
