### ISSUE TITLE
"App not installed" error

### ISSUE THREAD

**Issue by klingai-dev** [omkarmoghe/Pokemap#271]
I just started getting "App not installed" error for the current build and not being able to install it. I have a nexus 5x android 6.0.1. "Unknown source" checked. I was able to install the previous build from several days ago (about dev-rev163 or 164). I uninstalled it and just downloaded dev-rev389 apk today. It gives "App not installed" after 5 sec. Now i went back to try dev-rev163, I can't install that either. Same error. Is any permission changed in the app or app signature setting conflicts?

**Comment by sheikhsabayyal** [comment]
no permissions changed. The issue is at your end.  Just installed the 389 version without any issue.

Try restrting the device and install again

**Comment by klingai-dev** [comment]
Issue fixed. I think the uninstall of the previous one crashed. So it was still in my system but not showing icon. Rebooted and  found the app and uninstalled. Re install new build successfully. 

Suggestion: are we considering alter version number now? I know it's testing build but should it be 0.9.1 0.9.2 other than version 1.0? That way I can keep multiple version to test performance too. Great work though.
