### ISSUE TITLE
Countdown timer on marker tooltip does not display correctly when single digit seconds are left. 

### ISSUE THREAD

**Issue by rbryson74** [omkarmoghe/Pokemap#275]
If a pokemon marker has any time left where the number of seconds is zero through nine it will not display correctly. Where it would show 10:05 it instead shows 10:5

examples: 
Expires in: 8:8
Expires in 0:5

![screenshot_20160727-192018 1](https://cloud.githubusercontent.com/assets/11877300/17198107/d26ed08c-542f-11e6-89e6-9aece787fb82.png)

**Comment by comann** [comment]
Merged in and Fix.
