### ISSUE TITLE
Fix Pokestops.

### ISSUE THREAD

**Issue by ghost** [omkarmoghe/Pokemap#276]
Pokestops won't show farther than 3steps away while they could normally go farther, is this a bug or intentional? I'm confused as to why it does that. (Even if I set the steps at 5, it would still show only 3steps away)

**Comment by s7092910** [comment]
Already working on a fix, noticed it earlier today.

**Comment by Lionir** [comment]
Awesome! I'll be keeping an eye on the updates as always, awesome work! :3

**Comment by socrates2510** [comment]
Easy fix. It's in the queue.

**Comment by comann** [comment]
Merged in and Fixed.
