### ISSUE TITLE
Graphical issues while scanning.

### ISSUE THREAD

**Issue by ghost** [omkarmoghe/Pokemap#278]
If I long press to scan in an area while another area is being scanned, it will cause various graphical issues.

**Comment by Lionir** [comment]
Any fixes for this coming?.

**Comment by socrates2510** [comment]
Not sure about the graphical glitch. Can you add a screenshot?

**Comment by Lionir** [comment]
@socrates2510 It should be easy to replicate. Simply start scanning at a certain spot then while it is scanning, start scanning another area. Anyhow, here's a screenshot : http://imgur.com/apEwtuX

**Comment by socrates2510** [comment]
Yup. I thought it was that. I'm fixing it.

**Comment by Lionir** [comment]
@socrates2510 it will be released in v0.1?

**Comment by comann** [comment]
Fixed.
