### ISSUE TITLE
Suggestion: Boosted Pokestops

### ISSUE THREAD

**Issue by Sn3akySl0th** [omkarmoghe/Pokemap#280]
Is it in the cards for us to get boosted Pokestops? Also I don't know if there is a way to pull timers when a stop is boosted so that we can know how much time is remaining. Both of these would be great to see.

**Comment by s7092910** [comment]
It will show lured Pokestops right now, they look purple. We might add a timer for Milestone 0.2

**Comment by Sn3akySl0th** [comment]
I passes one earlier and I don't think it was purple. I'll check again next time I see one. Thank for the reply.

**Comment by comann** [comment]
This has been implemented in an upcoming release.
