### ISSUE TITLE
Fresh install, unable to login via google account

### ISSUE THREAD

**Issue by jtcressy** [omkarmoghe/Pokemap#282]
Hi, I do not login with a direct PTC account, only with google. Every time I attempt to hit the google sign-in button, it immediately says "PTC Login Failed" even though i'm not using a PTC account. It doesnt even bring up the prompt to select an account. It just does nothing. I have the source downloaded to android studio and will attempt to do some debugging, and i've already searched current issues about this but can't find an answer. If there's a quick solution to this, i'm all ears.

**Comment by s7092910** [comment]
The quickest solution is to create a PTC account. The hardest solution is that Google seems to have changed a bit of how their links are working, causing the way we authenticate using Google.  I'll be taking a look at this to see if we can get things working properly again.

**Comment by maxkadur** [comment]
same problem here. Maybe this helps for fixing: Pokemon Go Map from [here](https://github.com/AHAAAAAAA/PokemonGo-Map) is still working with google accounts.

**Comment by tanishbaansal** [comment]
I am not able to login with my ptc accountand when I click Google login it is still saying ptc login failed and I check ptc server status at ispokemongodownornot.com and it says that the servers are OK ... I don't know what to do can someone please add a server status option in the app so we can see if it is online or not.

**Comment by s7092910** [comment]
@maxkadur The issue with the way that the python version does Google login is a security issue. And not everyone will use a fake google account.

**Comment by tanishbaansal** [comment]
So what should I do I can't login via ptc nor via Google....

**Comment by s7092910** [comment]
@tanishbaansal have you activated your PTC account?
