### ISSUE TITLE
[Question] Updates

### ISSUE THREAD

**Issue by ghost** [omkarmoghe/Pokemap#286]
Will there still be releases between V0.1 and V0.2 so we can beta test features and report bugs as we go?

**Comment by s7092910** [comment]
Yes we will be constantly pushing stuff to the develop branch which you can use to build an apk in Android Studios

**Comment by ghost** [comment]
@s7092910 I'm not experienced with Android Studio but I saw that someone was making apks if you click on "Download latest" in the README.MD, and downloaded the apk, will they still be published?

**Comment by s7092910** [comment]
That is up to the person that was doing that. Many of us haven't been doing that.

**Comment by ghost** [comment]
@s7092910 I hope he does, I really liked that and I'll want more than the features from v0.1 because I like to have to have tons of features :3

**Comment by Giggitybyte** [comment]
I'd be willing to run an automated build script on of my Raspberry Pi if the current person who is compiling them decides to stop.

**Comment by ghost** [comment]
@GiggityByte Awe, that'd be awesome.

**Comment by omkarmoghe** [comment]
apks are auto generated by our Travis CI config on each successful build.
