### ISSUE TITLE
Google login failed while authenticating. response.body() is null

### ISSUE THREAD

**Issue by thisismohitgupta** [omkarmoghe/Pokemap#287]
The google login Seems to have stoped working

**Comment by s7092910** [comment]
It is a know issue. I'm currently looking at it. We might end up disabling Google Login.

**Comment by Giggitybyte** [comment]
Permanently or temporarily?

**Comment by s7092910** [comment]
Till we can determine what Niantic's new Client ID is.

**Comment by ghost** [comment]
I liked Google Login since PTC's servers are much less stable.. I hope you guys can determine it fairly quick.

**Comment by thisismohitgupta** [comment]
people at Niantic are horses

**Comment by s7092910** [comment]
It seems that Niantic probably did not change their Client ID. It might be an issue with the google login. We still have no idea.

**Comment by thisismohitgupta** [comment]
PTC signup is shut down ?

**Comment by s7092910** [comment]
It seems both the google and PTC login are down, same with the game servers. It seems that is the issue and hopefully they can get the logins and servers back up.

http://ispokemongodownornot.com/

On a good note tho, due to this happening I have found an easier way for people to login with their google account. This will be coming soon.

**Comment by Giggitybyte** [comment]
Both the Pokemon GO servers and the PTC servers are down right now.
https://go.jooas.com/

Edit: Ninja'd.

**Comment by Giggitybyte** [comment]
> ... I have found an easier way for people to login with their google account.

@s7092910 Sweet!

**Comment by almasmaris** [comment]
@s7092910 @Giggitybyte GO servers is not down. I can play Pokemon go right now. But, the app still get error response.body() is null

**Comment by Giggitybyte** [comment]
They were down not too long ago. PTC login is still down.

**Comment by thisismohitgupta** [comment]
PTC login is back. But cant sign up, any progress

**Comment by Adiron147** [comment]
It worked for me earlier, but now I get PTC login error.
Are PTC servers down?

**Comment by DarkPointer** [comment]
Waiting for updates.

**Comment by almasmaris** [comment]
It seems google change something. Thats why 2 step verification is not working anymore. 
Spegeli version (https://github.com/Spegeli/PokemoGoBot-GottaCatchEmAll/issues/136) changes the program using GPSO and its working.

**Comment by caniev** [comment]
I am also not be login google

**Comment by s7092910** [comment]
Sorry guys. Yes I did fix the google login. I wasn't able to completely test it due to the pokemon go servers being down. So I went to sleep. I tested the new way just now and it does work. I will

**Comment by s7092910** [comment]
I will be pushing out a fix within the next few hours

**Comment by ryan786** [comment]
Still can't login using google account

**Comment by Gennocyde** [comment]
Can't login using either Google or PTC still on rev422

**Comment by ramosf123** [comment]
Yeah I can't use either logins on rev422

**Comment by NCD1998** [comment]
Yeah, no PTC or google logins on rev424 either for me.

**Comment by s7092910** [comment]
The servers are currently down. The google login fix hasn't been merged or put into a PR yet.
