### ISSUE TITLE
[Enhancement] Scanned Circle customization

### ISSUE THREAD

**Issue by Colbey** [omkarmoghe/Pokemap#288]
Add to settings area a configuration option for the `scanned circle` so at the very minimum you could set opacity. and ideally set a custom color to use or a color adhering to the current app theme.

the current color option is very overpowering visually when you are trying to discern map characteristics such as roads. It also clashes with a few of the current Marker annotations.

**Comment by socrates2510** [comment]
Lighter color picked.

Customizations left for v0.2+
