### ISSUE TITLE
Pokemon number showing wrong

### ISSUE THREAD

**Issue by tanishbaansal** [omkarmoghe/Pokemap#290]
I scanned a area and it should only 1 pokemon but the below bar where scanning text is shown it was showing 5 pokemon because I think I have filtered rattata and pidegy.. but it should show right number of pokemon even after filter.

**Comment by ghost** [comment]
It says there's 5 Pokemons but it only shows you those you want to see. That's what the filter does.

**Comment by socrates2510** [comment]
Makes more sense to show what's in the screen new. Fixed.

**Comment by tanishbaansal** [comment]
![screenshot_2016-07-28-13-25-55_com omkarmoghe pokemap](https://cloud.githubusercontent.com/assets/7449806/17207980/816a2bbe-54d4-11e6-87ab-2aa9f1e4274b.png)
Here itshows only 3 pokemon but shows 5 pokemon below

**Comment by chrosey** [comment]
it's possible due scanning. you see that habitak(bird) is in surrounded by 2 circles. maybe thats where it is count twice.

**Comment by tanishbaansal** [comment]
hmm.. okay maybe that was the problem but it's happening many times with different pokemon i think it should be fixed.

**Comment by tanishbaansal** [comment]
And should there be a easy way to login via google account because i have to re login many times if i restart the app and type the code shown in the app. I use PTC account when it is online

**Comment by socrates2510** [comment]
There are some pokémon that show as there but expired a second later. Those are still counted. Coming in a later fix. (the blinking pokémon that showed for a sec).

**Comment by comann** [comment]
Merged in and Fix.
