### ISSUE TITLE
[Question] Autoreg script.

### ISSUE THREAD

**Issue by Kolyall** [omkarmoghe/Pokemap#294]
While creating a new account of PTC, it doesn't ask to confirm your email by clicking of link in mail.
So... can anybody create a script for auto registration new account and than we could log in to Pokemap with this new account?

**Comment by s7092910** [comment]
You should have got an email from noreply@pokemon.com for your PTC to confirm your account.

**Comment by Kolyall** [comment]
@s7092910 I don't wait of receiving of an email, after reg I login to Pokemap, and it works properly

**Comment by Giggitybyte** [comment]
You have up to two days to confirm your email. After two days, you'll get login issues. Found this out the hard way.

Edit: I don't know if it would even be worth it (or even possible): perhaps the app could create temporary PTC accounts for scanning purposes. That would eliminate the need for the user to create their own dummy account and log in.

**Comment by Juols69** [comment]
With alot of coding a script could be made and added to this app to do what is requested, however, several important facts have been overlooked. I would like to take a moment to point a few out.

PTC accounts require an email address and by randomly creating email addresses the app would have to maintain a database of previously used email addresses so as not to duplicate. This database would undoubtedly grow rapidly causing the app to become very heavy, not to mention it would potentially  and eventually prevent new players from using thier own email addresses. Another problematic issue with the number of accounts created is the amount of space it would use on Niantic's already unstable servers causing a rapid memory shortages. This could be seen by Niantic as an attack and hold the makers of this app fully responsible for down times as well as any and all financial losses becuase of overloads.

While this app may currently  be running below there scope of concerns currently,  doing that would make it thier first priority.

That being said, it would actually be in everyone's best interests to simply sign up for our own PTC account and login like we currently do and don't forget to confirm your email within 48hrs as others have pointed out.
