### ISSUE TITLE
no time shown

### ISSUE THREAD

**Issue by turing95** [omkarmoghe/Pokemap#301]
can't see any time on the pokemon icon

**Comment by chrosey** [comment]
please specify what you mean by "on the pokemon icon"

**Comment by turing95** [comment]
i am going to post a snap, wait a sec

**Comment by turing95** [comment]
![screenshot_2016-07-28-13-53-40](https://cloud.githubusercontent.com/assets/9216914/17211630/e04e126c-54ca-11e6-8691-277f1e18e2cc.png)

**Comment by turing95** [comment]
is it server related??

**Comment by chrosey** [comment]
ok thats due to an outdated translation.
need update on values-it/strings.xml
@neissa

**Comment by turing95** [comment]
the translation i think is right, the problem is that i actually can't see any countdown on any pokemon

**Comment by chrosey** [comment]
you have to check the related english 
`<string name="expiring_in">Expires in: %1$d:%2$d</string>` 
vs italian
`<string name="expiring_in">"Scade tra: "</string>`

it misses some string format code like `%1$d:%2$d`

**Comment by chrosey** [comment]
this was changed with #234 
thats when it stopped working

**Comment by socrates2510** [comment]
I had fixed that in PR #297 :-/
