### ISSUE TITLE
[Suggestion] Gym icons

### ISSUE THREAD

**Issue by tabasavr** [omkarmoghe/Pokemap#302]
As I understand right now gym icons are downloaded from imgur and then cached. I thing it would be better if they were included in app and loaded as resources

**Comment by omkarmoghe** [comment]
right, gym and pokestop icons should be bundled.

**Comment by Cadiducho** [comment]
:+1:

**Comment by kyr0** [comment]
They were bundled in my first implementation. Then we had a discussion and we all agreed on not bundling them with the app because even those graphics hold a copyright of Niantic...
