### ISSUE TITLE
Google login failing with invalid_request

### ISSUE THREAD

**Issue by DarkPointer** [omkarmoghe/Pokemap#305]
Hello guys,

I am trying to use the pokemap and consistently facing google login failed so I tried to get the logcat debug log and got this in the log :

> 07-28 14:52:25.182 13660-13938/com.omkarmoghe.pokemap D/NetworkRequest: Received response in 400 ms.
>                                                                         URL: https://accounts.google.com/o/oauth2/device/code?client_id=848232511240-73ri3t7plvk96pj4f85uj8otdat2alem.apps.googleusercontent.com&scope=openid%20email%20https://www.googleapis.com/auth/userinfo.email. 
>                                                                         Headers:
>                                                                         Content-Type: application/json; charset=utf-8
>                                                                         Cache-Control: no-cache, no-store, max-age=0, must-revalidate
>                                                                         Pragma: no-cache
>                                                                         Expires: Mon, 01 Jan 1990 00:00:00 GMT
>                                                                         Date: Thu, 28 Jul 2016 12:52:25 GMT
>                                                                         P3P: CP="This is not a P3P policy! See https://support.google.com/accounts/answer/151657?hl=en for more info."
>                                                                         X-Content-Type-Options: nosniff
>                                                                         X-Frame-Options: SAMEORIGIN
>                                                                         X-XSS-Protection: 1; mode=block
>                                                                         Server: GSE
>                                                                        Domain=.google.com;Path=/;Expires=Fri, 27-Jan-2017 12:52:25 GMT;HttpOnly
>                                                                         Alternate-Protocol: 443:quic
>                                                                         Alt-Svc: quic=":443"; ma=2592000; v="36,35,34,33,32,31,30,29,28,27,26,25"
>                                                                         Transfer-Encoding: chunked
> 07-28 14:52:25.192 13660-13938/com.omkarmoghe.pokemap D/NetworkRequest: Response body:
>                                                                         {
>                                                                           "error" : "invalid_client"
>                                                                         }

P.S: Removed set-cookie from the log.

Since I have no experience with OAuth2 I can't figure out where's the problem exactly.

I hope this problem gets solved.

Thanks.

**Comment by tabasavr** [comment]
Same for me but I think this is duplicate of [#287](287)

**Comment by DarkPointer** [comment]
I realize by looking at issue : https://github.com/omkarmoghe/Pokemap/issues/287

That the client_id has been changed and waiting for new one :) 

Thanks people, waiting to be solved after getting the new client_id.
