### ISSUE TITLE
SLACK INVITES

### ISSUE THREAD

**Issue by omkarmoghe** [omkarmoghe/Pokemap#31]
USE THIS LINK INSTEAD: https://pokemap-android-slack.herokuapp.com/

**Comment by LinkOut** [comment]
priv8@hotmail.it

**Comment by betrisey** [comment]
samuel@sam.ninja
Thanks

**Comment by finalpk** [comment]
finalpkpb@gmail.com

**Comment by MikePT28** [comment]
mpesate@gmail.com

**Comment by MikePT28** [comment]
ninjadark28@gmail.com

**Comment by soundlicious** [comment]
clash.reptilia@gmail.com

**Comment by socrates2510** [comment]
socrates.sp at gmail

**Comment by cristhianescobar** [comment]
escobarcristhian18@gmail.com

**Comment by kutukoff** [comment]
artemkutukov@gmail.com

**Comment by ShamisK** [comment]
khan.shamis@gmail.com

**Comment by rohanjain1** [comment]
rohanjain1@gmail.com
And let's mush people!! :D 
niantic can close down the holes in the API at any time.

**Comment by comann** [comment]
corey.mann@variableinc.com

**Comment by blbaker** [comment]
brandon@vlgux.com

**Comment by onkelkethe** [comment]
info@onkel-kethe.de
Thanks

**Comment by vishwasc20** [comment]
vishwasc20@gmail.com

**Comment by switchkiller** [comment]
crimerule.01@gmail.com
emailbarung@gmail.com

**Comment by brvtl** [comment]
peter@garbers.me

**Comment by marmikshah** [comment]
me@marmikshah.com
Thanks!

**Comment by switchkiller** [comment]
crimerule.01@gmail.com
emailbarung@gmail.com

**Comment by kristijandraca-xx** [comment]
[email removed]

**Comment by KBernard-nx** [comment]
nivek564@gmail.com

**Comment by mph121** [comment]
spamrightherepls@gmail.com

**Comment by omkarmoghe** [comment]
USE THIS LINK INSTEAD: https://pokemap-android-slack.herokuapp.com/
