### ISSUE TITLE
The Steps parameter doesn't seem to work

### ISSUE THREAD

**Issue by morninggrey** [omkarmoghe/Pokemap#311]
I'm setting steps to 5, but I only ever see the 1 or 2 pokemon in my immediate vicinity

**Comment by omkarmoghe** [comment]
can you post a screenshot or some logs or something? thanks

**Comment by Giggitybyte** [comment]
Are you using the latest dev build?

**Comment by Alanc33** [comment]
Steps worked fine at least on yesterdays build can't verify new build. I ran 20 steps on the build yesterday.

**Comment by morninggrey** [comment]
I synced just now, and same results, attaching screenshots

**Comment by DoraKlikOpDora** [comment]
At new build steps works fine for me, are you sure there are more Pokemons nearby?

**Comment by morninggrey** [comment]
Hardcoding steps to 5 in code works, but trying to set it through the app in the drop down list doesn't.  Maybe there's a 'save changes' button I'm not seeing or something, but I don't think so.

**Comment by DoraKlikOpDora** [comment]
There is no save button, it should create little rounds around you, then it creates a circle around you (like google does with GPS) and then there can be 2 rows more of little circles. Since the servers are hanging between up and down, that can be the problem

**Comment by CarstenHouweling** [comment]
Works fine for me

**Comment by morninggrey** [comment]
Ok I guess it's not affecting anyone else and I can work around it
