### ISSUE TITLE
Pokemon Go server disconnect constantly

### ISSUE THREAD

**Issue by ghost** [omkarmoghe/Pokemap#315]
When logged in with a google account, it will find pokemons and keep saying that it's unable to connect to pokemon go servers rapidly while finding other pokemons. Quite weird.

**Comment by DoraKlikOpDora** [comment]
Pokemon Go servers are hanging between up and down, this may cause this problem. Keep an eye on http://ispokemongodownornot.com and check if that is the problem.

**Comment by Sn3akySl0th** [comment]
I'm having issues logging in using PTC. I have to hit sign in multiple times before it will actually go through.

**Comment by DoraKlikOpDora** [comment]
@clefebvre81 Also look at the website http://ispokemongodownornot.com. The PTC login status is also given on that site.

**Comment by Sn3akySl0th** [comment]
I was. When I try and it fails that is the first thing I look at. It has been saying up and I continue to have issues.

**Comment by fess89** [comment]
@clefebvre81 this is a server problem, it may depend on where you are connecting from

**Comment by TDrakeHI** [comment]
Sounds like this is a duplicate of #329.

**Comment by comann** [comment]
No longer need login in upcoming release.
