### ISSUE TITLE
Build fails with incompatible Gradle plugin

### ISSUE THREAD

**Issue by PetrGasparik** [omkarmoghe/Pokemap#32]
Android Studio 2.1.2 

Error running app: This version of Android Studio is incompatible with the Gradle Plugin used. Try disabling Instant Run (or updating either the IDE or the Gradle plugin to the latest version)

How to handle this wqithout disabling Instant Run? What is correct version of Gradle?

**Comment by Sejadis** [comment]
installing android studio 2.2 preview should fix that (at least it did for me)
