### ISSUE TITLE
Is it working?

### ISSUE THREAD

**Issue by PetrGasparik** [omkarmoghe/Pokemap#33]
Stupid questions, but - is this WIP or full-feature?

So far, in Android app, I can see a map, in debug in Android Studio I can see that user is logged on pokémon site,
but I see only map, no Pokémon icons.

:)

**Comment by omkarmoghe** [comment]
WIP homie. if you wanna contribute feel free. we are working on getting the pokemon from the server right now.

**Comment by PetrGasparik** [comment]
I thought so, no problem, I just couldn't see the status of project :) and because it is referenced from working project, I assumed it works. Thanks for the response, I'll contribute if I find something I can do.

**Comment by omkarmoghe** [comment]
Yeah no prob man. Definitely shoot over a PR if you feel like it :)
