### ISSUE TITLE
not working anymore?

### ISSUE THREAD

**Issue by ward0** [omkarmoghe/Pokemap#330]
the APK is not working anymore?

**Comment by chrosey** [comment]
what do you mean by not working? latest dev-branch works. latest pre-build also

**Comment by firemonk3y** [comment]
i have tried several builds, including ones from a few days ago that were working fine until last night but now I am unable to login with either PTC or Google account when both accounts work fine in app itself and also in other projects.

**Comment by styadp1** [comment]
Same error for me too. Unable to login from either account.
![screenshot_20160729-103700](https://cloud.githubusercontent.com/assets/20726468/17252220/cbe97e56-5579-11e6-921e-1280fd21d4fc.png)

**Comment by Gennocyde** [comment]
you have to log in twice with google and it goes in. has been so for a while now

**Comment by styadp1** [comment]
Yup! Works fine when I login with google twice. Thanks! 👍

**Comment by omkarmoghe** [comment]
Hey guys, I think the issue is in our auto login which might be doing PTC by default. We'll look into it ASAP.

**Comment by rbryson74** [comment]
The PTC login works if you do it 3 times. One long wait until the error. a short wait to error, and then the actual login. It's pretty weird.

**Comment by firemonk3y** [comment]
yeah PTC works after 3 tries like you said, really weird!

**Comment by comann** [comment]
I am no longer seeing the PTC login after 3 times....It works for me.

**Comment by rbryson74** [comment]
I see it most when having just uninstalled/reinstalled. I just tried it again and still got the Long fail/short fail/success pattern. With the main dev builds being more stable reinstalling often is happening less so it's not really happening as often.
