### ISSUE TITLE
Incomplete Hexagonal scan area?

### ISSUE THREAD

**Issue by styadp1** [omkarmoghe/Pokemap#341]
Is it normal to show few un-scanned spots in this hexagonal area? 

![2016_07_29_11_07_45_11_11_24_11_13_16_11_25_26](https://cloud.githubusercontent.com/assets/20726468/17253590/5cc71f82-557f-11e6-92ef-9bb3e442e9ac.gif)

and also why does it show "Unable to contact Pokemon server...."  at the bottom?

**Comment by GiantForkLift** [comment]
I'm having this exact same problem. Is it searching too fast? This wasn't an issue the versions before yesterday.

**Comment by styadp1** [comment]
Not fast. I guess it's considering that split second gap as a loss of connection.

**Comment by Colbey** [comment]
this is a duplicate of #329

**Comment by CarstenHouweling** [comment]
There is an insane amount of duplicates lately...

**Comment by cwizard** [comment]
This is happening because the scanner is requesting data too fast.  Suggest modifying NianticManager.java to fix.

**Comment by splitbux** [comment]
New to all this. What would i add to NianticManager.java to slow down data requesting?

**Comment by CarstenHouweling** [comment]
@splitbux change all the 33's to 133's
