### ISSUE TITLE
Updating GPS icon fails?

### ISSUE THREAD

**Issue by styadp1** [omkarmoghe/Pokemap#342]
When we long press on the map, a GPS icon shows up and all the nearby Pokemon are scanned. But it looks like this GPS icon is being displayed on multiple locations when I long press on the map several times at several spots. 
![screenshot_20160729-113123](https://cloud.githubusercontent.com/assets/20726468/17253837/700e25bc-5580-11e6-8aac-332bf897874a.png)

**Comment by styadp1** [comment]
Here is the gif
![2016_07_29_11_44_59_11_47_49](https://cloud.githubusercontent.com/assets/20726468/17254525/31343c34-5583-11e6-8157-51637d53962b.gif)

**Comment by CarstenHouweling** [comment]
Confirmed
