### ISSUE TITLE
[Gramatical Mistake] Bad Spanish translation

### ISSUE THREAD

**Issue by iamvicbailon** [omkarmoghe/Pokemap#346]
In the menu, to "Mostrar unicaciones escaneadas", should be "Mostrar ubicaciones escaneadas".
Just for the spanish language.  
![f1b49690-da85-49d5-b855-a8981a71b43b](https://cloud.githubusercontent.com/assets/17035346/17261003/46cd452a-5599-11e6-8e8e-56310a25af5a.jpg)

**Comment by DoraKlikOpDora** [comment]
I will make a pull request.

The English texts there still are, can you translate them too, so I can change that too? Thanks!

**Comment by iamvicbailon** [comment]
Yes, I can translate that, based on the english file

**Comment by DoraKlikOpDora** [comment]
@iamvicbailon 
To be translated:

PresetTheme  
Are you sure you want to log out?  
YES 
NO
Search steps
Show Lured Pokémon
Other
Theme
Default
Pokémon to show (filter)
Will spawn here, scan again in a while
Google login failed
Failed to Find GPS Location
Expires in: %1$d:%2$02d
Google login failed
Please allow locations in order to use the app
Allow
App settings
Disclaimer
Searching&#8230;
No new catchable Pokémon have been found.
OK
%1$s (%2$d minutes, %3$d meters)
Searching&#8230; found %1$d Pokémon so far.
Preset Themes
Will make this selection look pretty in the future. Select a theme:

**Comment by iamvicbailon** [comment]
Ok, I made a commit for this ;)

**Comment by iamvicbailon** [comment]
@DoraKlikOpDora 

Translation:

Tema predefinido

¿Estás seguro que quieres cerrar sesión?

SI 
NO
Tamaño de búsqueda
Mostrar Pokémon atraído
Otro
Tema
Por defecto
Pokémon para ver (filtrar)
*Background service -> "Ejecución en segundo plano"
Aparecerán aquí, vuelve a buscar en un momento
Falló el inicio de sesión de Google
Falló al encontrar la ubicación por GPS
Desaparece en: %1$d:%2$02d
Falló el inicio de sesión de Google
Please allow locations in order to use the app
Por favor, habilite los permisos de localización para usar esta aplicación
Permitir
Ajustes de aplicación
Negar
Buscando…
No se ha encontrado algún nuevo Pokémon atrapable
OK
%1$s (%2$d minutos, %3$d metros)
Buscando… encontrando %1$d Pokémon hasta ahora.
Temas preestablecidos
Esta sección hará que se vea bonito en el futuro. Selecciona un tema:

`<resources>
    <string name="app_name" translatable="false">Pokémap</string>
    <string name="action_settings">Ajustes</string>
    <string name="action_clearmap">Limpiar mapa</string>
    <string name="action_logout">Cerrar sesión</string>
    <string name="pref_file_key" translatable="false">com.omkarmoghe.pokemap.PREFERENCE_FILE_KEY</string>
    <string name="pref_theme">Tema preestablecido</string>
    <string name="logout_prompt_message">¿Estás seguro que quieres cerrar sesión?</string>
    <string name="yes">SI</string>
    <string name="no">NO</string>
    <string name="pref_cat_user_account">Cuenta de usuario</string>
    <string name="pref_warning">ADVERTENCIA!!!: No uses tu cuenta principal de juego para esta aplicación!
        Recomendamos, crear y usar una cuenta falsa de Pokémon Trainer Club con diferente correo y contraseña.</string>
    <string name="pref_username">Usuario</string>
    <string name="pref_username_key" translatable="false">UsernameKey</string>
    <string name="pref_default_username">Victor B</string>
    <string name="pref_password">Contraseña</string>
    <string name="pref_password_key" translatable="false">PasswordKey</string>
    <string name="pref_default_password" translatable="false">***</string>
    <string name="pref_cat_general">General</string>
    <string name="pref_pokestops_title">Mostrar Poképaradas</string>
    <string name="pref_pokestops_key" translatable="false">pokestops_checkbox</string>
    <string name="pref_gyms_title">Mostrar Gimnasios</string>
    <string name="pref_gyms_key" translatable="false">gyms_checkbox</string>
    <string name="pref_scanned_title">Mostrar área escaneada</string>
    <string name="pref_scanned_key" translatable="false">scanned_checkbox</string>
    <string name="pref_pokemons_to_show_key" translatable="false">Pokémon para ver (filtrar)</string>
    <string name="pref_search_steps">Tamaño de búsqueda</string>
    <string name="pref_search_steps_key" translatable="false">search_steps</string>
    <string name="pre_lured_key" translatable="false">lured_checkbox</string>
    <string name="pref_lured_title">Mostrar Pokémon atraído</string>
    <string name="pokestop" translatable="false">Poképarada</string>
    <string name="pref_cat_service">Background Service</string>
    <string name="pref_service_enable_title">Enable</string>
    <string name="pref_service_enable_key" translatable="false">background_poke_service</string>
    <string name="pref_service_refresh_title">Frecuencia De Actualización</string>
    <string name="pref_service_refresh_summary">¿Con qué frecuencia el servicio se actualizará en segundos?.</string>
    <string name="pref_service_refresh_key" translatable="false">service_refresh_rate</string>
 backg
    <string name="toast_credentials">No se puede ingresar. Por favor verifique su cuenta de usuario</string>
    <string name="title_activity_poke_map">Pokémon cerca</string>
    <string name="login_warning"><Data><![CDATA[ Se recomienda crear y utilizar una cuenta falsa de Pokémon Trainer Club (PTC) con una contraseña diferente y correo electrónico o utilizar una cuenta de Google no conectada a su cuenta de Pokémon Go. A medida que el uso de esta aplicación podría dar lugar a su cuenta siendo <b>baneada</b>
    ]]></Data></string>
    <string name="prompt_username">Usuario PTC</string>
    <string name="prompt_password">Contraseña PTC</string>
    <string name="action_sign_in">Iniciar sesión</string>
    <string name="error_field_required">Campo requerido</string>
    <string name="title_activity_maps">Mapa</string>
    <string name="login_warning_title">Advertencia:</string>
    <string name="request_credentials_title">Ingrese su usuario de Pokémon Go</string>
    <string name="search_pokemon_map_suggestion">(Mantén presionado para cambiar la ubicación de búsqueda)</string>
    <string name="default_string">Por defecto</string>
    <string name="pokemon_to_show">Pokémon para ver (filtrar)</string>
    <string name="action_relogin">Re-Ingresar</string>
    <string name="ban">Baneado</string>
    <string name="minutes">"minutos"</string>
    <string name="pokemon_disappearing_in">"Desaparece en: "</string>
    <string name="pokemon_expired">Expirado</string>
    <string name="position_picked">Posición seleccionada</string>
    <string name="seconds">"s"</string>
    <string name="toast_localization_waiting">Esperando por ubicación&#8230;</string>
    <string name="toast_login_successful">Inicio de sesión satisfactorio.</string>
    <string name="toast_map_not_initialized">Problema al inicializar mapa de Google</string>
    <string name="toast_server_unreachable">Imposible conectar con los servidores de Pokémon GO. Los servidores pueden estar caídos.</string>
    <string name="toast_token_expired">El token de ingreso ha expirado. Obteniendo uno nuevo.</string>
    <string name="toast_user_found">Encontrado!</string>
    <string name="toast_login_error">Error al iniciar sesión.</string>
    <string name="toast_internal_error">Un error interno ha ocurrido. Esto puede suceder cuando estás fuera de línea o los servidores están inactivos.</string>
    <string name="toast_ptc_login_error">Inicio de sesión PTC fallido</string>
    <string name="toast_google_login_error">Inicio de sesión de Google fallido</string>
    <string name="enable_location_permission_title">Habilitar permisos de localización</string>
    <string name="enable_location_permission_message">Por favor habilite los permisos de localización para usar esta aplicación</string>
    <string name="toast_no_location">Error para encontrar la ubicación GPS</string>
    <string name="expiring_in">Expira en: %1$d:%2$02d</string>
    <string name="google_login_failed">Inicio de sesión de Google fallido</string>
    <string name="permition_message">Por favor permita los servicios de localización para usar esta aplicación</string>
    <string name="allow">Permitir</string>
    <string name="app_settings">Ajustes de aplicación</string>
    <string name="disclaimer">Denegar</string>
    <string name="toast_searching">Buscando&#8230;</string>
    <string name="toast_pokemon_found_count">"Pokémon encontrado"</string>
    <string name="pokemon_found_none">No se ha encontrado nuevo Pokémon para capturar.</string>
    <string name="pokemon_found_new">%1$d nuevo Pokémon atrapable encontrado.</string>
    <string name="notification_service_title">Servicio de Pokémap</string>
    <string name="notification_service_scanning">Buscando</string>
    <string name="notification_service_stop">Detener servicio</string>
    <string name="notification_service_pokemon_near">%1$d Pokémon cerca.</string>
    <string name="notification_service_pokemon_in_area">%1$d Pokémon en el área:</string>
    <string name="meters">metros</string>
    <string name="gym">Gimnasio</string>
    <string name="button_ok">Ok</string>
    <string name="notification_service_inbox_line">%1$s (%2$d minutos, %3$d metros)</string>
    <string name="toast_still_searching">Buscando&#8230; encontrando %1$d Pokémon a lo lejos.</string>
    <string name="preset_themes_title">Restablecer tema</string>
    <string name="theme_activity_text">Esta sección hará que se vea bonito en el futuro. Selecciona un tema:</string>
</resources>`

If you need more help, tell me 😄

**Comment by DoraKlikOpDora** [comment]
Would be fixed in https://github.com/omkarmoghe/Pokemap/pull/361

Thanks!

**Comment by rohanjain1** [comment]
@iamvicbailon Thanks for the assist bud. We'll include it ASAP.
