### ISSUE TITLE
[Question] Spawning system

### ISSUE THREAD

**Issue by ghost** [omkarmoghe/Pokemap#357]
How accurate is the pokemons that will spawn option? Isn't the spawning system random?

**Comment by s7092910** [comment]
Right now, the API sometimes returns pokemon with a negative time till disappears. There is a connection that these might be pokemon that stay up for 30 minutes long.

**Comment by ghost** [comment]
@s7092910 I'm not sure I understand, the API gives a signal for pokemons that WILL spawn for 30minutes?..

**Comment by s7092910** [comment]
No, the way that the API works is that if the pokemon has not been spawned, it shouldn't be sending a list of those pokemon to the client. But we are seeing pokemon with a negative time till hidden. 

Normally a pokemon has 15 minutes from spawn till it disappears. The ones with negative time till hidden it is believe they have 30 minutes from spawn till it disappears.

**Comment by ghost** [comment]
@s7092910 I still don't get it but I'll just leave it to you and the others, thank you for trying though. Anyhow, they should be accurate, right? Also, there seems to be an issue that you might want to check out : https://travis-ci.org/omkarmoghe/Pokemap

**Comment by rohanjain1** [comment]
@Lionir ATM the app alerts you to pokemon which will spawn in the near future.. <10-15 minutes. It's based on an observation we had on the data being returned by the servers.
Enjoy !
