### ISSUE TITLE
FAB animation not working

### ISSUE THREAD

**Issue by tabasavr** [omkarmoghe/Pokemap#358]
It's broken again. Was fixed by [PR 333](https://github.com/omkarmoghe/Pokemap/pull/333) but was broken again by [PR 328](https://github.com/omkarmoghe/Pokemap/pull/328)

**Comment by chrosey** [comment]
thats right...
i moved snackbar to mainactivity to handle it going lost.  #333 handled it inside the map fragment. is there somebody who know a fix?

**Comment by chrosey** [comment]
this should do it
see #384

**Comment by jLynx** [comment]
Please re-open the issues if this is not fixed in the current release
