### ISSUE TITLE
Caused by: org.greenrobot.eventbus.EventBusException: Subscriber class com.omkarmoghe.pokemap.views.MainActivity and its super classes have no public methods with the @Subscribe annotation

### ISSUE THREAD

**Issue by chmodx** [omkarmoghe/Pokemap#370]
Please help. I don't know what it is doing

**Comment by LinkOut** [comment]
This error means that MainActivity have a: `EventBus.getDefault().register(this);`, wich means it register to receive events from EvenBus, and there's not a
 `@Subscribe
    public void onEvent(PoJo event) {//Handle the received event}` method on the MainActivity.
