### ISSUE TITLE
Found Pokémon doesn't appear

### ISSUE THREAD

**Issue by maxkadur** [omkarmoghe/Pokemap#372]
Some Pokémon appear only very shortly while scanning.. it says that 1(or more) Pokémon was found but it isn't displayed. And I have no filter activated.

**Comment by Eg1M** [comment]
I have same issue too. Some Pokemons permanently stays with notification: will spawn here, scan again in a while. Others just appear and  suddenly disappear.

**Comment by Eg1M** [comment]
Tried to change PTC account. It didn't help

**Comment by Eg1M** [comment]
Location is Russia

**Comment by VIPkiller17** [comment]
Same here, some pokemon just flash when a scan is started and don't reappear. I can confirm that they were actually there as i caught them afterwards.

**Comment by comann** [comment]
Duplicated. https://github.com/omkarmoghe/Pokemap/issues/383
