### ISSUE TITLE
[BUG] Expiration time doesn't appear

### ISSUE THREAD

**Issue by iamvicbailon** [omkarmoghe/Pokemap#374]
I click en the Pokémon and the expiration time doesn't appeare.
![a407637c-14cc-40bc-a9e8-5b8113d31d9c](https://cloud.githubusercontent.com/assets/17035346/17272920/4390cc9e-5669-11e6-8d48-19c07c4133b6.jpg)

**Comment by DoraKlikOpDora** [comment]
In the last Spanish translation a typo has been made with the variable, I will change this and create a pull request. 

EDIT:
Pull request: https://github.com/omkarmoghe/Pokemap/pull/376
