### ISSUE TITLE
[suggestion] gmaps-key

### ISSUE THREAD

**Issue by TAImatem** [omkarmoghe/Pokemap#378]
Add an option to use your own gmaps key with instructions to getting properly working one (if it's possible, ofc) in case the app will become too popular

**Comment by DoraKlikOpDora** [comment]
There already is a flag for this: -k

**Comment by TAImatem** [comment]
Dora, I'm talking about apk version, not python, you're in a wrong thread probably

**Comment by DoraKlikOpDora** [comment]
Oh, sorry, my bad. Had the wrong project I was thinking of

**Comment by Kazpers** [comment]
It's a good idea, I think, although I don't know enough about Android development to know if it can be taken out of the AndroidManifest.xml file. For now you can change it there before building...

**Comment by chrosey** [comment]
the gmaps key option is coming with #304
