### ISSUE TITLE
[SUGGESTION] Use Creative Commons - Icon Set

### ISSUE THREAD

**Issue by RomanBf** [omkarmoghe/Pokemap#380]
How about using [this icon set](https://www.iconfinder.com/iconsets/151-1) instead of copyrighted ones, and bundle them with the app? 
PNG and SVG available.

**Comment by CarstenHouweling** [comment]
They're pretty ugly tbh. 

And the app isn't going to be in the store anyways.

**Comment by ghost** [comment]
@CartsenHouweling It would still be good if the app wasn't copyright infringing.

**Comment by s7092910** [comment]
@Lionir Technically the way we have set up the app. Legally in Canada, the US, and the EU, you can download copyrighted material or link to copyright material on a website, even if they don't own a license to or own the copyright. So long as you don't share it with other people.

**Comment by ghost** [comment]
@s7092910 Then you can't put copyrighted material on Github since anyone outside of those countries could get it.

**Comment by 0xD34D** [comment]
I'm sure people have forks but @Lionir is correct, this Github project can be considered infringing and all Niantic has to do is file a claim with github and the project will be suspended, and the burden will be on the project owner to try and get it back up.  Seen this happen with projects I've used.

If you think they are ugly, find something that you like that does not infringe ;)

**Comment by ghost** [comment]
@0xD34D Or even better, make your own. I'm scared that this Project will be taken down due to recent events.

**Comment by ghost** [comment]
According to someone in the comments, those icons ARE copyrighted... Just thought I'd point that out.

**Comment by jLynx** [comment]
Please re-open the issues if this is not fixed in the current release
