### ISSUE TITLE
blank map

### ISSUE THREAD

**Issue by turing95** [omkarmoghe/Pokemap#381]
i think there is some problem beacuse the scan always shows a blank map, with zero pokemon found

**Comment by momo0206** [comment]
Same Problem

**Comment by tabasavr** [comment]
Probably same as #377

**Comment by Ayysir** [comment]
They shut down the api

**Comment by styadp1** [comment]
I'm still able to see few Pokémon 

![screenshot_20160731-114055](https://cloud.githubusercontent.com/assets/20726468/17277563/e3cc008e-5713-11e6-8e53-17db330ab134.png)

**Comment by antony1316** [comment]
Not sure if it's totally shutdown. The AHAAAAAAA/PokemonGo-Map project still works on my PC. That's the project this port was based on. So what's the difference is the question?

**Comment by axsddlr** [comment]
@antony1316 likely limit call requests and changed some stuff

**Comment by comann** [comment]
Refer to this issue. https://github.com/omkarmoghe/Pokemap/issues/383
