### ISSUE TITLE
Not showing Pokestops

### ISSUE THREAD

**Issue by NozderkaJakub** [omkarmoghe/Pokemap#394]
The pokemap doesn't show pokestops (with option enabled in settings) since update 0.3

**Comment by LinkOut** [comment]
Duplicate of #383

**Comment by NozderkaJakub** [comment]
@LinkOut 
#383 is about not showing pokemons

**Comment by robinodling** [comment]
My experience is that pokestops show up sometimes, and sometimes not.. Most often the latter.

**Comment by juanro49** [comment]
I have same problem, since lastest updates, pokestops doesn't swow :(
