### ISSUE TITLE
Can I use Android Studio 2.1 ?

### ISSUE THREAD

**Issue by leovarmak** [omkarmoghe/Pokemap#401]
Does this thing work with Android Studio 2.1 ? I use Max OS X

**Comment by CarstenHouweling** [comment]
Please read the f***ing manual before opening an issue. ❤️

**Prerequisites**  

Android Studio v2.2 or later 
All 24.0.1 build tools, SDKs, and support libraries installed. ( This can be done by launching SDK Manager )  
Android Device or Emulator with API v17 or later
Pokemon Go Account / Google Account

**Building**

Download the latest Android Studio dev preview. (> 2.1)
Launch the SDK Manager and make sure you have the 24.0.1 build tools, N SDKs, and 24.0.0 support libraries installed.
Open the project and hit Build > Clean project

**Comment by LinkOut** [comment]
Yes, im using it on 2.1...

**Comment by leovarmak** [comment]
@CarstenHouweling I read the manual. But in one of the issues, the team member asked someone to check if works on 2.1. But there was no reply. So I opened this issue keeping in mind that you people might have forgotten to update the readme
