### ISSUE TITLE
No pokemon/stops/gyms

### ISSUE THREAD

**Issue by robe0635** [omkarmoghe/Pokemap#403]
I updated to the current version and now when i run a search it shows nothing, tried in different locations and also running a manual "long press"

**Comment by s7092910** [comment]
Dude to recent changes by Niantic on the server all mapping has been broken. The community is still working on a fix.

**Comment by robe0635** [comment]
Ahh okay, thanks heaps for the info man

**Comment by comann** [comment]
There is an upcoming release in the pipeline.
