### ISSUE TITLE
Pgoapi was updated. Rejoice! :D

### ISSUE THREAD

**Issue by ghost** [omkarmoghe/Pokemap#405]
Can't wait to finally use this again, it'll be awesome!

**Comment by xakiru** [comment]
True https://github.com/keyphact/pgoapi

**Comment by magiblot** [comment]
See the last messages at https://github.com/omkarmoghe/Pokemap/issues/383 for the latest news

**Comment by comann** [comment]
We will be diverging from pogo api due to the direction of the repo is not the same direction we are heading.
