### ISSUE TITLE
0 pokemon found

### ISSUE THREAD

**Issue by icrona** [omkarmoghe/Pokemap#408]

**Comment by CarstenHouweling** [comment]
@icrona Seriously? Get out.

**Comment by tristaoeast** [comment]
I'm having the same issue, both with a PTC and a Google account, right in the centre of Lisbon, where are plenty of pokemon, that I can assure you. Also gyms and pokestops are not showing at all. And yeah, I'm using the latest release

**Comment by oriojke** [comment]
Same here, no pokemon/pokestops/gyms are shown on the map with the latest release.

**Comment by hhagmans** [comment]
It's the old release, it's not fixed now..
They are still working on it.

**Comment by ghost** [comment]
Pokemon, gyms and pokestops aren't visible on build 538

**Comment by prelude0000** [comment]
Same issue here.
Btw. Could Dev add version number to some menu. It would be useful for demended persons like me :P

**Comment by zorakirby** [comment]
@icrona Don't post issues that are already posted #383
