### ISSUE TITLE
Login failed 

### ISSUE THREAD

**Issue by sameerbatavia** [omkarmoghe/Pokemap#411]
I get and ptc login failed but can login to ptc using latest apk

**Comment by myristica** [comment]
gmail login fails as well

**Comment by Anu6is** [comment]
Guys, please try to keep up with the documentation/comments that the developers set out. 
The app has not yet been updated since the API change by Niantic. Even if you were to log in the app will not work at this point in time. Please wait for the next release before creating new issues.

**Comment by comann** [comment]
The upcoming release does not support user login anymore.
