### ISSUE TITLE
why login is required

### ISSUE THREAD

**Issue by ghost** [omkarmoghe/Pokemap#412]
I thought this project connect to 

https://github.com/PokemonGoMap/PokemonGo-Map

own private map server directly? 
Is this project android client for the server or not?

**Comment by s7092910** [comment]
We are a port of the that project. We aren't making a client for it as it would mean either just setting up a webview or modifying the the server to allow calls to it.

It was decided to make a standalone app

**Comment by ghost** [comment]
i got it.. I just thought this client is same as ios version. 
Thanks.
