### ISSUE TITLE
Nothing appears on the map

### ISSUE THREAD

**Issue by ghost** [omkarmoghe/Pokemap#42]
I've entered my Google account, says the login is invalid - later I found out that I should test with a Trainer account.
I did so, reentering my login details in settings. After pressing re-login, nothing happens; it does show my location properly though.
Here is a [logcat](https://gist.github.com/georgenetu/751e8209b60d7db10d261800189c97ad) output.

Uninstalling the app, entering the credentials again doesn't bring any feedback, as well.

**Comment by blastagator** [comment]
Just built and same thing.  Did you use master or dev branch?

**Comment by ghost** [comment]
The dev branch. Should I try the master branch?

**Comment by omkarmoghe** [comment]
Yeah nothing should show up on the map. We are working on displaying Pokemon right now. Haven't merged into a public branch yet! Stay tuned

**Comment by ghost** [comment]
Thanks a lot for the quick reply. Do you have a list where you keep your "todo", "in progress" tasks? I'm very interested in contributing. (I can't join Slack, too many invites for now, will wait)

**Comment by blastagator** [comment]
Let me know if there is anything you guys need.  I'm more of a c++ guy but I've been working on getting into js

**Comment by CanOrhan** [comment]
Hey @georgenetu! We keep a ToDo list here: https://slack-files.com/T1TQY34KE-F1TSY25UL-10400392c2

**Comment by socrates2510** [comment]
https://pokemap-android.slack.com/files/omkarmoghe/F1TSY25UL/TODO

**Comment by ghost** [comment]
Very nice, thank you.

**Comment by omkarmoghe** [comment]
Yeah we're trying to get people in the Slack, but we've been hit with the limit until people start accepting invites :/
