### ISSUE TITLE
Update for new release?

### ISSUE THREAD

**Issue by GiantForkLift** [omkarmoghe/Pokemap#421]
Sorry to be a nag about this, but is there an ETA on when the working update will be released? I checked in issue 383 which is closed and there hasn't been much said for a bit. Just curious!

**Comment by s7092910** [comment]
Just before we were about to release, PTC threw a wrench in our plan. As what we were doing, with what PTC did, we could only have 2300 active users on at the same time to be able to provider a decent search speed for everyone. 

We tried looking at doing a different search method to lower the amount of calls to the pokemon go servers. That didn't work as well as we had planned.

But we found a work around, it will also give us a faster loading speed on app startup. So it should be the next day or two.

**Comment by GiantForkLift** [comment]
Awesome. Thanks for the quick response. Y'all are great!

**Comment by zorakirby** [comment]
https://i.ytimg.com/vi/qf9OfGhMLFg/hqdefault.jpg

**Comment by Ek20000** [comment]
Best.Developers.Ever

**Comment by mastescarhead1** [comment]
Do we have an update on this? It's been 4 days since the last "eta"

**Comment by jLynx** [comment]
@mastescarhead1 we have finally figured out what we have been trying to do, so I am going to estimate 2-3 more days max

**Comment by s7092910** [comment]
We are in the testing phase now. If all goes well, the apk will be uploaded.

**Comment by hybridtracer** [comment]
I've been reading that today's update broke a lot of trackers...Does this throw a wrench in the plans? Some still work but others don't so it's a bit confusing.

**Comment by mastescarhead1** [comment]
Should still be fine. Most I see are still working.

**Comment by jLynx** [comment]
Our app is still working and is not effected

**Comment by Ek20000** [comment]
Awesome work guys

**Comment by jLynx** [comment]
If all goes well, we should be able to release in the next 5-10 hours

**Comment by jLynx** [comment]
Ok guys we are ready to release, we have the apk all sorted. We just need one of the repo admin to upload it!

**Comment by GaurAfro** [comment]
Awesome

**Comment by hybridtracer** [comment]
Is there a changelog/feature liat that can be shared while waiting for apk by any chance?

**Comment by Ubimo** [comment]
@DarkN3ss61
Still not seeing any new upload :-(

**Comment by Ek20000** [comment]
:/  just be patient @Ubimo

**Comment by Anu6is** [comment]
It's happening!!!
Release is out. - https://github.com/omkarmoghe/Pokemap/releases/tag/v1.1.0

**Comment by Sn3akySl0th** [comment]
I can't get past the captchas

**Comment by jLynx** [comment]
What's the problem @clefebvre81?

**Comment by Sn3akySl0th** [comment]
It keeps freezing after a couple and doesn't continue.

**Comment by jLynx** [comment]
@clefebvre81 can you tell me if you can still scroll the page up and down while you think it's stuck?

**Comment by Anu6is** [comment]
Took me nearly an hour to get through them.
It seemed frozen but I could scroll the pages. I suppose it was mainly impatience but it didn't feel like it was progressing after almost a 1 minute wait.

**Comment by GorgeousDan** [comment]
Can't install for some reason. Go through the unknown sources process, after I see the permissions I hit install and its gets through the install and says "App not installed"

**Comment by Anu6is** [comment]
@GorgeousDan Do you have the old version of the app still installed? If so try deleting it first.

**Comment by micha279** [comment]
Have you uninstalled the old version first? You need to do so otherwise install will fail

On 24 August 2016 21:13:31 CEST, GorgeousDan notifications@github.com wrote:
Can't install for some reason. Go through the unknown sources process,
after I see the permissions I hit install and its gets through the
install and says "App not installed"

##

**Comment by jLynx** [comment]
@Anu6is  It should only take 1-2 minutes. So I will have to look into that and see why it's taking so long...

**Comment by GorgeousDan** [comment]
@Anu6is I made sure to uninstall the old one first

**Comment by GorgeousDan** [comment]
I just tried again and it installed all a sudden lol

**Comment by blackmaskmen** [comment]
@GoegeousDan Can you send the apk link here

**Comment by Anu6is** [comment]
@DarkN3ss61 
I should clarify. 

It's not that moving from 1 to 10 took that long on its own. For example, I reached 9 once and waited about 1 minute and it never transitioned to 10. I closed the app and had to start over and the same loading delay occurred on other items during the process. 

So, attempting to go through all ten while closing and starting over consistently is what extended the time frame for completion.

**Comment by jLynx** [comment]
@Anu6is Does it come up with the loading text under the check box once you have checked it?

**Comment by s7092910** [comment]
It sounds like a network issue.

**Comment by Anu6is** [comment]
@DarkN3ss61 
Yes, loading appears... it's possible it was simply impatience and network issues like @s7092910 suggested.

**Comment by jLynx** [comment]
@Anu6is still strange as the total time to complete the 10 should only be about 1-2 minutes

**Comment by GiantForkLift** [comment]
You guys rock! Thanks so much for getting this out to us. The app works beautifully.

Now a quick question for you. Since it no longer requires an account for us to login, what are the possibilities of getting banned? And on that same note, how does niantic determine if someone is using an app like this to scan?

**Comment by poekrel** [comment]
Thank you guys so much! Seriously though the work that has been committed to this is greatly appreciated by so many of us. I noticed that the scanning speed has been greatly increased. Has Niantic ceased throttling server requests or have you found a way around it with all your awesomeness? And do you think that the new scanning speed (which I'm sure everyone loves) will effect the longevity of the app (as far as the possibility of drawing in more attention from the Niantic developers)?
