### ISSUE TITLE
Selling the source?

### ISSUE THREAD

**Issue by scarecr0w12** [omkarmoghe/Pokemap#422]
I found this

https://www.sellmyapp.com/downloads/pokemap-find-nearby-pokemon-go/?utm_source=facebookads&utm_medium=pokemap&utm_campaign=mainoffers

Someone selling the source?

**Comment by Ginso** [comment]
Seems to be just another one of those apps where user can entry pokemons they found. I don't think it retrieves the information from the server

**Comment by s7092910** [comment]
That app is in no way affiliated with our app.
