### ISSUE TITLE
Version 1.1.0 released! 

### ISSUE THREAD

**Issue by jLynx** [omkarmoghe/Pokemap#424]
https://github.com/omkarmoghe/Pokemap/releases/tag/v1.1.0

**Comment by Anu6is** [comment]
@DarkN3ss61 
Posting this here because I don't want to add a new "issue" post. 
Can someone close the older issues that may not be relevant to the new release. Of course some of the same bugs or enhancement requests may still apply, but that are definitely some posts that can be closed.
