### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by Helianza** [omkarmoghe/Pokemap#427]
When I try to install this apk, my phone works normally, then told me : "Aplication not installed" (In french, so I translate, maybe badly).

Anyone has this problem ? Is there a solution for this ?

**Comment by GorgeousDan** [comment]
@Helianza Make sure to uninstall the old version first.

**Comment by Helianza** [comment]
As long as I know, I never use it before.
So I can't uninstall it. If I try with lucky patcher, I have INSTALL_FAILED_UPDATE_INCOMPATIBLE.

**Comment by poekrel** [comment]
I had this issue as well. Was able to get it working by installing the previous release, then uninstalling, followed by installing the current release.

**Comment by Helianza** [comment]
Ok. Thanks.
And where can I find it ? :D

**Comment by Helianza** [comment]
I tried with the previous app debug, And it's ok now !
Thanks !

**Comment by jLynx** [comment]
Awesome, please close this issue if it is solved @Helianza
