### ISSUE TITLE
Application won't open

### ISSUE THREAD

**Issue by masaf2** [omkarmoghe/Pokemap#428]
Do you know if the application is already down ? It was working just fine this morning but now it won't open at all. I tried to clear all the app data and reopen (and redo the recaptcha thing) but it's still not working. Is there anyone else who has the same problem ?

**Comment by jLynx** [comment]
Hmmm. Working for me. Can you give it a go now and see if its working now for you?

**Comment by s7092910** [comment]
Are you getting stuck on the loading screen? Or do you mean you can't login at all?

**Comment by Giggitybyte** [comment]
After completing the Captchas, the app crashes.

**Comment by Eric678** [comment]
After completing captchas, hangs "Loading" waited 10 min? Restart wants me to do captchas again - forget it!

**Comment by masaf2** [comment]
Yeah it was stuck on the loading screen forever but now it's working. In fack it started to work again around 6.00 PM (GMT-5) so maybe it was because of the rush hours... anyway thank you that's an amazing app (I almost catched my first wild Vaporeon with this app) ! Thank you very much for your work !!!

**Comment by jLynx** [comment]
If this problem is still not fixed, please reopen this issue
