### ISSUE TITLE
App doesn't work on ARC Welder

### ISSUE THREAD

**Issue by dotplay** [omkarmoghe/Pokemap#429]
I tried to open the app within google chrome, but I receive a blank screen during the "Complete the reCAPTCHA" process. No captcha, just the title and the 1/10 label. therefore I can't fulfill anything and complete the setup.

Maybe it's impossible or hard to fix, or maybe its very easy. I'm just informing anyway.

Chrome version: 51
OS: Windows 7

**Comment by jLynx** [comment]
I don't understand, How can you try it in chrome? Its an Android app

**Comment by dotplay** [comment]
ARC Welder.
https://developer.chrome.com/apps/getstarted_arc
It's supposed to run on a Chromium OS, but it works on windows with some bugs.

**Comment by s7092910** [comment]
From what I can tell, ARC Welder has issues with Android's webview. Which is what we are using to display the captcha. Sadly no one knows of a fix to this. It would be great if we could fix it. But at this time it doesn't look like there will be a fix.

**Comment by dotplay** [comment]
Ok! Thanks for replying!
