### ISSUE TITLE
What's the latest release?

### ISSUE THREAD

**Issue by Ubimo** [omkarmoghe/Pokemap#430]
This one?
https://github.com/omkarmoghe/Pokemap/releases/tag/dev-rev545
Or this one?
https://github.com/omkarmoghe/Pokemap/releases/tag/dev-rev547
Is there a changelog somewhere?

**Comment by jLynx** [comment]
https://github.com/omkarmoghe/Pokemap/releases/download/v1.1.0/Pokemap_release_1.1.0.apk
