### ISSUE TITLE
[Question] Does the 1.1.0 relese use my "Pokemon GO" account?

### ISSUE THREAD

**Issue by ofiras** [omkarmoghe/Pokemap#433]
As in title - I have noticed it does not ask for a login account. Is it automatically using my google Pokemon GO account? Or does it use a random ptc account?
If it is using my account - isn't it dangerous? can't I get banned?
And thank you for this amazing app!

**Comment by jLynx** [comment]
No it does not use your account or anything to do with it

**Comment by ofiras** [comment]
Great, Thank you!
