### ISSUE TITLE
Down at the moment?

### ISSUE THREAD

**Issue by chooyee20** [omkarmoghe/Pokemap#435]
Doesn't seem to be working. Showed a PTC login fail.

**Comment by vilnytskyi** [comment]
It's common situation and it happens sometimes. The moment is not the reason to open an issue.

**Comment by Sn3akySl0th** [comment]
Are the development builds working or is it just the released version? I couldn't get the development build to show anything.

**Comment by jLynx** [comment]
We have had some issues with the servers IP changing causing users to not be able to connect. I am going to fix this today so we shouldn't have this issue. 

@clefebver81 no. Please re the readme. We are close source so we will not be posting any source code
