### ISSUE TITLE
[suggestion] Label to show account being used + option to change login credentials

### ISSUE THREAD

**Issue by skryptus** [omkarmoghe/Pokemap#436]
Apologies if I missed something in the v1.1.0 release, but it's hard to know which user is being used. Since I didn't provide any login credentials, I'd assume it to be using my Google account, but it didn't ask to confirm its access to my Google account either. 

In any case, along with the information of which account the app is currently using, an option should be provided to change the account; many of us are probably using our Google account in-game,  so we'd rather reduce the risk of getting that one banned.

**Comment by jLynx** [comment]
This app does not use any of your accounts, so there is no need for this

**Comment by crashandburn4ever** [comment]
Quick question on the same topic. I was leaving work and it switched from WiFi to my mobile data. When I tried logging in to the app, it showed me "PTC Login failed". What login is used to access the app? Will it use any of my gmail accounts? Or is it an account generated by the app?

**Comment by jLynx** [comment]
@crashandburn4ever Account generated by the app
