### ISSUE TITLE
Official website not working

### ISSUE THREAD

**Issue by Limeliz** [omkarmoghe/Pokemap#440]
This repos [github wiki](https://github.com/omkarmoghe/Pokemap/wiki) links to the following URL as the "[Official Website](https://jz6.github.io/PoGoMap/#)", but that page gives a 404 error: https://jz6.github.io/PoGoMap/#

**Comment by jLynx** [comment]
That site is no longer running. The official url is http://pokemapgo.xyz, but we haven't put anything on it just yet

**Comment by Limeliz** [comment]
@DarkN3ss61 My antivirus software F-Secure blocks that site for me.
![image](https://cloud.githubusercontent.com/assets/5267867/18144069/284b4fde-6fc5-11e6-9fe1-01b0b7157994.png)

Same with the other two websites (jlynx and darkn3ss) in your profile. What's up with that?

**Comment by jLynx** [comment]
I'm have no idea why it is doing that, I will try and contact them and get to the bottom of this

**Comment by jLynx** [comment]
I have just contacted them and now waiting for a response. It seems that they pick up lots of false positives

**Comment by jLynx** [comment]
I have contacted F-Secure and they have now fixed this
