### ISSUE TITLE
App doesn't save settings and needs to rescan to show pokemon

### ISSUE THREAD

**Issue by GiantForkLift** [omkarmoghe/Pokemap#443]
Upon downloading the recent version I noticed that the app doesn't save my settings. I always deselect to show gyms and poke stops but everytime I close the app the settings reset and shows gyms and pokestops.

The other issue I noticed is it's not bringing up all the available Pokémon in the scanned area. I scanned a popular hot spot at our local university and scanned one time and it showed a couple of Pokémon and thought that was odd. So I scanned a handful of more times to get everything to show up. Could this be because the scanning speed was increased? Great app by the way!

**Comment by s7092910** [comment]
I'm looking in to it right now.

**Comment by GiantForkLift** [comment]
Looks like the settings not saving has been fixed in v1.1.5. Thank you! I'm looking at the scanning issue again, I'll let you know what I find.

**Comment by GiantForkLift** [comment]
Looks like this has all been resolved. Thank you!!
