### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by rgdam** [omkarmoghe/Pokemap#445]
I've been receiving this message "An internal errorocurred. This might happen when you are offline or the servers are down" for a few days, since the last 2 updates I think. My connection is ok and I have already reinstalled the app, cleared cache etc. Any suggestions about how to overcome this? Thanks for the app!

**Comment by jLynx** [comment]
Try the latest version (1.1.6) and let me know if that fixes it

**Comment by rgdam** [comment]
Tried 1.1.6 and still doesn't work. Moto X2 with Android 6.0 here

**Comment by s7092910** [comment]
Both phones have google play and the google play services installed?

**Comment by rgdam** [comment]
Google play services and Google play installed

**Comment by s7092910** [comment]
Any thing else installed that might have an impact on apps on your devices? Like xposed framework?

**Comment by rgdam** [comment]
No, it isn't rooted

**Comment by Slv3r** [comment]
Hi, i have the same exact problem of rgdam; on version 1.1.0 the app worked well. But after few days the error appeared ("An internal error occurred. This might happen when you are offline or the servers are down") on the same version (1.1.0); then i tried all the new versions (1.1.6 too) but the error is still here. I've tried to reinstall the app but i got the same result. Maybe something related to the accounts used by the app? i can't even find a way to clear/recreate them to test this theory; I tried to clean app data/reinstalling but the app still use the old accounts (i can't find a way to force the re-creations). Thanks for your job!

P.S. my phone is a Nexus 5 with Android 6.0 stock.

**Comment by hqtrung** [comment]
Xiaomi mi 5 stock miui 8, the app used to work but after update,  it keeps report connection error.  Updated to 1.1.6 can not fix.  Uninstalled with clear cache and data didn't bring catpcha again and didn't work either.

**Comment by rgdam** [comment]
Same here, couldn't bring captcha again, even after cleaning cache, reinstalling etc

**Comment by s7092910** [comment]
In 1.1.6 we changed it so that if you already have accounts tied to your device you won't be able to go to the captcha. I'll look at adding an option to free the accounts tied to your device and to create some more accounts.

**Comment by Slv3r** [comment]
Hi, thanks! Just wondering, those accounts are stored in phone memory or server side? There's no way by deleting something on the phone to force to create new accounts?

**Comment by s7092910** [comment]
They are stored server side at the moment. We will implement a caching feature soon so if our server is down, you can still use the app. But to change accounts, you will need the server to be up.

**Comment by Slv3r** [comment]
I've updated the app to version 1.2.0 but, unfortunately, the problem still here. I've tried to clear data, but nothing changed, no captcha shows. Can you please manually erase data associated with my device to use this great app again pls? What info i have to provide to you? Thanks!

**Comment by jLynx** [comment]
@Slv3r Please try the new version(1.2.1), then if the problem is still happening, tap the reset accounts button
