### ISSUE TITLE
Version 1.1.5 Login issue

### ISSUE THREAD

**Issue by skylex77** [omkarmoghe/Pokemap#447]
I try in 3 different phones, all of them show this error, the only one that works was the one I installed the 1.1.1 and then update, after this it seems the 1.1.1 store the login data and the error don't show, but if you use another phone where you never installed the app it shows the server connection failed error :(

![2016-09-02_204318](https://cloud.githubusercontent.com/assets/20802056/18222239/4aada0ce-714e-11e6-8e5b-a5adf34d8121.jpg)

**Comment by ghost** [comment]
I can report the same issue on my device. it always fails to connect to servers. Confused as to why.

**Comment by jLynx** [comment]
Can you guys try clear your data for the app then try open it again?

**Comment by s7092910** [comment]
Looking into it, I think I found the issue. Working on a fix again. It was an edge case that I thought I caught but did not.

**Comment by jLynx** [comment]
Fixed https://github.com/omkarmoghe/Pokemap/releases/download/v1.1.6/PokeMap_1.1.6.apk
