### ISSUE TITLE
[BUG] Pokestops and gyms sometimes do not show up during a scan session. 

### ISSUE THREAD

**Issue by CubeCraft751** [omkarmoghe/Pokemap#448]
Let's say you have area A and area B. There is a gym and pokestop in each area. I scan area A, and it shows the stop and gym. I then scan area B, and it doesn't show the stop and gym. I clear my map and rescan both areas, still only shows the stuff from area A. The only way to fix this is to disable and then re-enable pokestops and gyms in settings. Let's say after you do this, you scan area B and it's stop and gym show up. You then scan area A, nothing. Repeat the whole cycle. It seems that you can only see one set of pokestops/gyms per scanning session without resetting the settings. I am using version 1.1.6. In addition, this only happens periodically, but it happens on over 50% of scans.

**Comment by s7092910** [comment]
I'm unable to reproduce this. Has anyone else been able to reproduce it?

What it might be is that you might be scanning areas really far away from each other, thus causing the pokemon go servers to return nothing when the scan for the pokestops and gyms appear.

**Comment by CubeCraft751** [comment]
This is definitely a possibility, the scans are ~3800 ft away from each
other, and I'm scanning pretty rapidly. I think I'll close the issue and
just chalk it up to user error :)

Also I just want to say, thank you for the speedy response!
