### ISSUE TITLE
New Feature Selecting Pokemon

### ISSUE THREAD

**Issue by GiantForkLift** [omkarmoghe/Pokemap#455]
I think it's a great idea, the only thing I would suggest is to highlight the Pokemon you have selected so you can clearly see which one you have clicked on. 

On top of the timer shown in that feature, would it be possible to also include the exact time a Pokemon will despawn?

**Comment by s7092910** [comment]
Will do. We decided we are going to revamp a bit of how we do our image system. So we will include highlight the pokemon selected.

**Comment by jLynx** [comment]
Done in 1.2.4
