### ISSUE TITLE
Sugestion: Move the reset account to settings

### ISSUE THREAD

**Issue by jorgdebont** [omkarmoghe/Pokemap#457]
Could the reset account button be moved to the settings menu, I tend to press it by accident when trying to reset the map.

**Comment by zorakirby** [comment]
I second this. The location for the "reset accounts" button is terrible and far too easy to accidentally click. It doesn't even ask for confirmation

**Comment by zorakirby** [comment]
I've already reset my accounts 3 times by accident :/

**Comment by jLynx** [comment]
Yes we are moving it and having a prompt asking if you are sure you want to reset your accounts

**Comment by jLynx** [comment]
Moved to settings in 1.2.4
