### ISSUE TITLE
Shouldn't have PokemonOuterClass.java hard coded.

### ISSUE THREAD

**Issue by podarsmarty** [omkarmoghe/Pokemap#46]
Shouldn't have PokemonOuterClass.java hard coded. Should be generated from same .proto file as https://github.com/AHAAAAAAA/PokemonGo-Map

**Comment by podarsmarty** [comment]
https://github.com/omkarmoghe/Pokemap/pull/45 should have the changes need to have android studio generate it when compiling the apk.

**Comment by omkarmoghe** [comment]
Not sure I understood the question, it was generated from the `.proto`

**Comment by podarsmarty** [comment]
@omkarmoghe ahh all I meant was it should be generated from the. proto file at compile time. This way it's much easier to keep in sync with the other repo. Also the android protobuf plugin ends up using javanano instead of the full one.

**Comment by podarsmarty** [comment]
merged in
