### ISSUE TITLE
Highlighted Pokemon

### ISSUE THREAD

**Issue by GiantForkLift** [omkarmoghe/Pokemap#465]
Thanks for adding the highlight feature! The only issue I see with it is that the highlight stays even after deselecting a Pokémon. Otherwise, it's great! I also like the larger Pokémon icons by the way.

**Comment by cartifon** [comment]
Is possible to ser here.

![screenshot_20160912-165915](https://cloud.githubusercontent.com/assets/7103578/18450711/757ed700-790a-11e6-80d1-12863704cdfd.png)

**Comment by s7092910** [comment]
Are you switching apps or closing the app between switching selected pokemon?

**Comment by GiantForkLift** [comment]
No, I'm not.  I can get it to switch between the Pokémon just fine, but when I try to deselect by pressing elsewhere in the map, the highlight stays. It's not a huge issue since it disappears when they despawn.

Also, I've noticed that some of the icons for the Pokémon are not enlarged. Like with Pidgeot, geodude, mankey, and zubat, to name a couple. Is it suppose to be that way? Or something on my end? I'm on the Galaxy Note 4 by the way (if that helps).

**Comment by s7092910** [comment]
Ok, I think I narrowed down the issue with the highlighted pokemon.

About the images, we recently changed how we are handling images. So with that, the images do have some issues that we still have to sort out. With it there will be an option to set the size of the icons.

**Comment by GiantForkLift** [comment]
Awesome, sounds great! I've never dealt with anyone who actually cares about getting an app update like you guys have. Makes life great for all of us. Thanks for listening!

**Comment by GiantForkLift** [comment]
For the moment I had the update before resetting accounts, this was fixed. Thanks!!
