### ISSUE TITLE
v1.2.4 I can't connect server by data mobile mode

### ISSUE THREAD

**Issue by goslife** [omkarmoghe/Pokemap#466]
I can use app v1.2.0-1.2.1 over data mobile when I update to v1.2.4 I cannot use app over data mobile and show pop up.
"**Pokemap Server Connection Failed**" 
"Failed check to see if there was a new version"

But I can use by wifi mode.

**Comment by jLynx** [comment]
Can you try again now, and see if we have fixed it?

**Comment by goslife** [comment]
with v1.2.4 my phone block permission to use data mobile, now I set permission to allow use data mobile and can app normal. Thank you for your app.
