### ISSUE TITLE
[Enhancement] Pokemon Stats

### ISSUE THREAD

**Issue by Anu6is** [omkarmoghe/Pokemap#468]
Is it at all possible, with the data received from the servers, to display the Pokemon IV's when a Pokemon is selected. So along with the time remaining we see ATK: XX | DEF: XX | STM: XX. 

I'm not sure what exactly is contained in the server responses that's retrieved, but if at all possible, such a feature would be greatly appreciated.

**Comment by renxida** [comment]
My guess is that the atk, def, etc are generated at random. My basis is that multiple people can catch the same pokemon if the others initiate the 'battle' before the first one finishes capturing, and that different players catch pokemon with different CPs. But I cannot rule out that they are just catching the same pokemon IV-wise at different levels.

Though I see no reason for niantic to give the IVs before capture is complete.

**Comment by s7092910** [comment]
It is possible for this to happen. The issue is we have to be careful with it to not get the accounts banned.

**Comment by Anu6is** [comment]
@RADiEnCe  I've confirmed with a few friends that despite the varying CPs, the IVs are the same for the same spawn. So while we may not be able to predict the CP of the Pokemon you will get, the IVs are definitely available.

@s7092910  Thanks for the response. I guess I simply assumed that once you got a response from Niantic's servers, all that information is readily available for use just like the Pokemon de-spawn time. If however, the logistics of actually displaying this can increase the chance of an account ban then it's probably not worth it.

**Comment by renxida** [comment]
Good to know. Thank you.

**Comment by renxida** [comment]
My immediate reaction would be to a actually behave like a regular player
and catch'em all. But that's just plain botting. Are there any tests on
whether accounts get banned because of this?

**Comment by Anu6is** [comment]
@RADiEnCe  Trust me, I catch everything I come across anyway. There are times however when I'm in the office and something I want spawns and I have to weigh do I step out right now or not, lol. I figured knowing the IV in advance would be the difference between "I could let this one pass" or "I could risk being fired for this"

**Comment by Anu6is** [comment]
This sheds some light as to what getting IVs entails - https://github.com/PokemonGoMap/PokemonGo-Map/pull/1272

Now I understand the potential to be banned.
