### ISSUE TITLE
Unable to complete reCAPTCHA

### ISSUE THREAD

**Issue by GiantForkLift** [omkarmoghe/Pokemap#469]
I'm unable to get passed the first reCAPTCHA. Once I complete the first one it just sticks on the reCAPTCHA completed/verified and eventually says the verification has expired.

I have uninstalled and reinstalled, tried going back to a previous version and installing that way, restarted my phone, and switched between using data and WiFi. I have no success with it. Any idea what I should try?

**Comment by jLynx** [comment]
Thanks for letting us know, we have had a few other reports of this issue so we are looking into it

**Comment by skylex77** [comment]
Yeah same here, new update don't work captcha, after you complete the first one it get stuck there

**Comment by jLynx** [comment]
This should be fixed in the latest version (1.2.6)

**Comment by GiantForkLift** [comment]
It is. Thank you guys so much!
