### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by GiantForkLift** [omkarmoghe/Pokemap#477]
Does niantic have a way to detect if you have a scanning app on your device? I only bring this up because I am unable to catch anything with a high cp. I'm a level 27 and I have caught 6 Dragonite, not a single one has been over 900 CP. Dragonite aren't the only ones I have this problem with either. 

Is this Niantic trying to prevent us from using a scanning app or do I just have terrible luck?

**Comment by k4n30** [comment]
terrible luck

**Comment by renxida** [comment]
I had no scanner and I had the same
