### ISSUE TITLE
Autorotate - restarts map

### ISSUE THREAD

**Issue by tbar** [omkarmoghe/Pokemap#482]
If Android is set up to auto rotate screen then the app will restart the map when the screen changes from landscape mode to portrait mode (and vice versa).

This is seen in 1.4.4 and 1.4.5. Wasn't an issue in 1.3.2. I haven't used the versions in between...

**Comment by jLynx** [comment]
Fixed in 1.5.x

**Comment by tbar** [comment]
It is fixed when using the map. Same issue is still present in the loading screen.
