### ISSUE TITLE
No information about the Gyms (they are not shown on the map)

### ISSUE THREAD

**Issue by Borys74** [omkarmoghe/Pokemap#490]
Today I installed PokeMap 1.6.0. I have selected the option "Show Gyms", but the map does not display any Gyms. In version 1.5.2 this option work properly.

**Comment by Borys74** [comment]
Thank you for the quick fix. In version 1.6.1 option "Show Gyms" again working properly.

**Comment by amazingjessi** [comment]
Is youth map loading fine? I haven't been able to load it since last night, says it failed to find updated version? I have 1.6.1

**Comment by jLynx** [comment]
This is fixed now, sorry for any inconveniences, our server was being attacked.
