### ISSUE TITLE
response.header("Location") is null

### ISSUE THREAD

**Issue by kutukoff** [omkarmoghe/Pokemap#5]

**Comment by ifconfig** [comment]
try to set your login information in  getToken("", ""); (MainActivity.java)

**Comment by kutukoff** [comment]
Google+ username and password?

**Comment by ifconfig** [comment]
I have taken the one from Pokermon Trainer Club

**Comment by kutukoff** [comment]
Thx ! I will try

**Comment by dowadidi** [comment]
I have the same issue. And no success adding my login information.
![debug](https://cloud.githubusercontent.com/assets/3625639/16984983/e4c707ac-4e7d-11e6-8ca7-51c198b37a67.png)

**Comment by ZakharchenkoWork** [comment]
Solution is to use login and password from a pokemon trainer club,  which chould be passed to getToken("login", "pass");

**Comment by kutukoff** [comment]
Yep, its working ! Thx.
