### ISSUE TITLE
Cant Join The Slack

### ISSUE THREAD

**Issue by SdtBarbarossa** [omkarmoghe/Pokemap#53]
Hello dear Devs :-)

im very interested in this project (and willing to help) but i cant get into the damn slack.... the invites are always full ;-(

greetings, 
XDA Sdtbarbarossa

**Comment by CanOrhan** [comment]
Hey dude! Submit your email address to [this form](https://pokemap-android-slack.herokuapp.com/) and someone'll accept you asap.

**Comment by vamidi** [comment]
Hi dear Devs,

I want to join too but i am also getting an error. Is there still room?

greetings

**Comment by wjwolf79** [comment]
Ditto:  filling out the form gives a maximum invites sent message.  you either have a crap ton of people in it who aren't contributing, or have a 2 user limit.... =D

**Comment by CanOrhan** [comment]
@wjwolf79 Neither, actually. We have a crap ton of people who haven't accepted :( Gotta wait for @omkarmoghe to come online and purge the invites :)

**Comment by omkarmoghe** [comment]
Yo yo. So I read up on this and its based on acceptances. Even if I purge a bunch of invites the limit won't be lifted until people who signed up accept
