### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by pgoh4xor** [omkarmoghe/Pokemap#54]
/Users/xyz/AndroidStudioProjects/Pokemap2/app/src/main/res/values/styles.xml
Error:(4, -1) android-apt-compiler: [main] /Users/xyz/AndroidStudioProjects/Pokemap2/app/src/main/res/values/styles.xml:4: error: Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.DarkActionBar'.
Error:(8, -1) android-apt-compiler: [main] /Users/xyz/AndroidStudioProjects/Pokemap2/app/src/main/res/values/styles.xml:8: error: Error: No resource found that matches the given name: attr 'colorAccent'.
Error:(6, -1) android-apt-compiler: [main] /Users/xyz/AndroidStudioProjects/Pokemap2/app/src/main/res/values/styles.xml:6: error: Error: No resource found that matches the given name: attr 'colorPrimary'.
Error:(7, -1) android-apt-compiler: [main] /Users/xyz/AndroidStudioProjects/Pokemap2/app/src/main/res/values/styles.xml:7: error: Error: No resource found that matches the given name: attr 'colorPrimaryDark'.
Error:(11, -1) android-apt-compiler: [main] /Users/xyz/AndroidStudioProjects/Pokemap2/app/src/main/res/values/styles.xml:11: error: Error: No resource found that matches the given name: attr 'windowActionBar'.
Error:(12, -1) android-apt-compiler: [main] /Users/xyz/AndroidStudioProjects/Pokemap2/app/src/main/res/values/styles.xml:12: error: Error: No resource found that matches the given name: attr 'windowNoTitle'.
Error:(14, -1) android-apt-compiler: [main] /Users/xyz/AndroidStudioProjects/Pokemap2/app/src/main/res/values/styles.xml:14: error: Error retrieving parent for item: No resource found that matches the given name 'ThemeOverlay.AppCompat.Dark.ActionBar'.
Error:(15, -1) android-apt-compiler: [main] /Users/xyz/AndroidStudioProjects/Pokemap2/app/src/main/res/values/styles.xml:15: error: Error retrieving parent for item: No resource found that matches the given name 'ThemeOverlay.AppCompat.Light'.
/Users/xyz/AndroidStudioProjects/Pokemap2/app/src/main/res/values-v21/styles.xml
Error:(3, -1) android-apt-compiler: [main] /Users/xyz/AndroidStudioProjects/Pokemap2/app/src/main/res/values-v21/styles.xml:3: error: Error: No resource found that matches the given name: attr 'windowActionBar'.
Error:(4, -1) android-apt-compiler: [main] /Users/xyz/AndroidStudioProjects/Pokemap2/app/src/main/res/values-v21/styles.xml:4: error: Error: No resource found that matches the given name: attr 'windowNoTitle'.

**Comment by wjwolf79** [comment]
The code currently in the dev branch complies with no problems.  But I see your app name is "Pokemap2", so I'm guessing you copied it into another project or folder (if you already cloned the source previously)

but if your Android Studio is on the carany build, updated sdk's, etc, then once you clone it, run the clean project, you shouldn't have any errors on the compile.

**Comment by pgoh4xor** [comment]
Well Yes the App Name change was causing the issue when used Pokemap as folder name and app name it got compiled. Thanks a lot for pointing out.
