### ISSUE TITLE
Pre-compiled apk?

### ISSUE THREAD

**Issue by Miskerest** [omkarmoghe/Pokemap#55]
Why don't we provide a link to a pre-compiled apk (or include it in the repo)? I feel like it would reduce a lot of questions/issues being opened in the future.

**Comment by psamsonov** [comment]
Those exist, see https://github.com/omkarmoghe/Pokemap/releases/tag/dev-rev83

**Comment by filfat** [comment]
Made clearer with bf9e8235ec71c937548ede22eb91096eb0754d0b.
