### ISSUE TITLE
SLACK INVITES

### ISSUE THREAD

**Issue by omkarmoghe** [omkarmoghe/Pokemap#56]
Comment your email if you want an invite to the dev Slack. THIS IS FOR DEVELOPERS ONLY, NOT GENERAL QUESTIONS.

We will send invites periodically to avoid hitting the limit again.

**Comment by psamsonov** [comment]
peter__samsonov@hotmail.com

**Comment by wjwolf79** [comment]
wjwolf79@gmail.com

**Comment by penbob3** [comment]
plazmacatchermc@gmail.com

**Comment by slezadav** [comment]
slezadav@gmail.com

**Comment by ejaribeiro** [comment]
jjoaquimrribeiro@gmail.com

**Comment by IldeNet** [comment]
ildenet2@gmail.com

**Comment by Harlindonas** [comment]
b1gb0ssftw13@gmail.com

**Comment by ProjectBarks** [comment]
contact@brandonbarker.me

**Comment by MarcqGuillaumeVO2** [comment]
marcqguillaume@gmail.com

**Comment by marcqg** [comment]
marcqguillaume@gmail.com

**Comment by jastheace** [comment]
myanth@gmail.com

**Comment by SdtBarbarossa** [comment]
michzdimarco@gmail.com

**Comment by grubFX** [comment]
felix.grub@gmail.com

**Comment by mattbutlar** [comment]
mattxl@gmail.com

**Comment by Abhijay** [comment]
abhijayb@gmail.com

**Comment by k0mat** [comment]
kow.mateusz@gmail.com

**Comment by cristhianescobar** [comment]
escobarcristhian18@gmail.com

**Comment by s7092910** [comment]
chris.beda@gmail.com

**Comment by Scremerok** [comment]
krypiu.aleksandr@gmail.com

**Comment by Silenc3IsGold3n** [comment]
z14942744@gmail.com

**Comment by mongizaidi** [comment]
lmongizaidi@gmail.com

**Comment by luischavez** [comment]
leviathanumi@gmail.com

**Comment by rattlytocho** [comment]
rattlytocho@gmail.com

**Comment by livviest** [comment]
c.renfrow06@gmail.com

**Comment by grishka** [comment]
grishka93@gmail.com

**Comment by galo4kin** [comment]
galo4kin@gmail.com

**Comment by juanpablobr** [comment]
juanpablobr@gmail.com

**Comment by patil215** [comment]
neilpatil215@gmail.com

**Comment by JackCloudman** [comment]
maylo360xd@gmail.com

**Comment by supirman** [comment]
firman.droid@gmail.com

**Comment by patrickcurl** [comment]
patrickwcurl@gmail.com

**Comment by abdulhannanali** [comment]
@omkarmoghe Why don't you just create a gitter.im channel? It's what many open source projects use and it's free with no messages limit too

**Comment by katajump** [comment]
katajump@gmail.com

**Comment by wellart** [comment]
wellart@me.com

**Comment by pokedev** [comment]
pokedev16@gmail.com

**Comment by nerael** [comment]
dowdy.aaron@gmail.com

**Comment by JGreenlee** [comment]
m3il0@yahoo.com

**Comment by jorgereina1986** [comment]
jorgereina1986@gmail.com

**Comment by expy** [comment]
andrewip999 [AT] gmail.com

**Comment by ThanosFisherman** [comment]
psaridis@gmail.com

**Comment by ThanosFisherman** [comment]
`psaridis@gmail.com`

**Comment by 73u38** [comment]
Mongky23@gmail.com

**Comment by dcdom321** [comment]
Mustangmarching@gmail.com

**Comment by zombiesplat** [comment]
alan [AT] asteriskpound.com

**Comment by blacklight1025** [comment]
Blacklight1025@gmail.com

**Comment by sreimler** [comment]
thank you!

**Comment by christiancoleman** [comment]
christianlanecoleman@gmail.com

**Comment by tenfoldinaus87** [comment]
kyletutor87@gmail.com

**Comment by tenfoldinaus87** [comment]
tenfoldinaus@hotmail.com

**Comment by RomkaZVO** [comment]
romkaeliseev@gmail.com

**Comment by omkarmoghe** [comment]
^ invited ^

**Comment by sahilshekhawat** [comment]
sahilshekhawat01@gmail.com

**Comment by jesserockz** [comment]
jesserockz@gmail.com

**Comment by silverAndroid** [comment]
pererarushil1940@gmail.com

**Comment by giodep** [comment]
giodep2003@gmail.com

**Comment by pace-noge** [comment]
nasa.freask@gmail.com

**Comment by bstadden** [comment]
bstadden@gmail.com

**Comment by ezzye** [comment]
ezzy.elliott@gmail.com

**Comment by kyr0** [comment]
aron.homberg@gmail.com

**Comment by Vaiogreva** [comment]
Invite vaiogreva@gmail.com 
Pliase

**Comment by willyum000** [comment]
Willyum000@gmail.com

**Comment by hegazy** [comment]
ahmed.hegazy1192@gmail.com

**Comment by Hoollow** [comment]
mateuszkowalewski12@gmail.com

**Comment by Ramiloom** [comment]
Ramibot@gmail.com

**Comment by shugo-chara** [comment]
i@i-misaka.com THX

**Comment by begon123** [comment]
begon123@gmail.com

**Comment by stellariae** [comment]
zeigersteinsein@gmail.com

**Comment by GozhevDenis** [comment]
dnkosiris@gmail.com

**Comment by GaruGaru** [comment]
garuglieritommaso@gmail.com

**Comment by julprz** [comment]
pricefree@hotmail.fr

**Comment by nordicoder** [comment]
omkar.9194@gmail.com

**Comment by jsj** [comment]
jamesjacksonyes@gmail.com

**Comment by ghost** [comment]
projack8@gmail.com

**Comment by matatian** [comment]
Mtsmeadd2@gmail.com

**Comment by treyhoover** [comment]
treyhoover@gmail.com

**Comment by charlypeluch** [comment]
charlypeluch@gmail.com

**Comment by Ek20000** [comment]
Fradikamura@gmail.com

**Comment by skymesser** [comment]
skymessers@gmail.com

**Comment by vidarr101** [comment]
coder101@gmail.com

**Comment by vaibhavbarmy** [comment]
vaibhavbarmy@gmail.com

**Comment by parthmshah** [comment]
parthshah0610@gmail.com

**Comment by Nod1m** [comment]
ineo15s@gmail.com

**Comment by omkarmoghe** [comment]
^ INVITED ^

**Comment by anoxymoron** [comment]
jonathandhartley@gmail.com

**Comment by mr-glt** [comment]
colson72098@gmail.com

**Comment by zombiesplat** [comment]
alan@asteriskpound.com

**Comment by BioXeon** [comment]
lesandrstar@gmail.com

**Comment by kobejitsu** [comment]
salvi84@gmail.com

**Comment by Jayvd** [comment]
Learnandlearn4ever@gmail.com

**Comment by ICoupI** [comment]
lexa38522@gmail.com

**Comment by IshaanKr** [comment]
i.k.ishaan786@gmail.com

**Comment by rizfenrir** [comment]
fachrizky@outlook.com

**Comment by g1eagle** [comment]
g1eagle@gmail.com

**Comment by pokecatchy** [comment]
Edit: ... offline now ...

**Comment by RealErick** [comment]
realerickxiang@gmail.com

**Comment by NeroDOC** [comment]
nerodocinn@gmail.com

**Comment by jerriclynsjohn** [comment]
jerric@catalanlabs.com

**Comment by villagebike** [comment]
markvillagebike@gmail.com

**Comment by kintch** [comment]
kintch911@gmail.com

**Comment by David1469** [comment]
darchila14@gmail.com

**Comment by RockLee91** [comment]
Tizianocavalli140391@gmail.com

**Comment by sylar79** [comment]
sylar79 [at] gmail.com

**Comment by mwillems1994** [comment]
1994smeagol1994@gmail.com

**Comment by acc85** [comment]
acc85@sky.com

**Comment by Night111221** [comment]
bryancorona122@gmail.com

**Comment by joya0000** [comment]
yugijim@hotmail.com

**Comment by 7eemoo** [comment]
aak1996@live.com

**Comment by DeirhX** [comment]
deirh.mana@gmail.com

**Comment by rirze** [comment]
cheedella.sourabh@gmail.com

**Comment by z11h** [comment]
zridouh@live.com

**Comment by ekishiro** [comment]
pocketterz@gmail.com

**Comment by AhmedBelHadj88** [comment]
ahmedbelhadj88@gmail.com

**Comment by Sayujya** [comment]
me@sairijal.com

**Comment by ismaelvb** [comment]
ismael.vb@gmail.com

**Comment by hack3rjack** [comment]
hack3rjack@gmail.com

**Comment by sharadJay** [comment]
kmrshankys@gmail.com

**Comment by ajiyanuari** [comment]
ajiyanuari001@gmail.com

**Comment by ajiyanuari** [comment]
ajiyanuari001@gmail.com

**Comment by rekDen** [comment]
denis@berkovich.de

**Comment by ghost** [comment]
bittu.8445@gmail.com

**Comment by aelean** [comment]
dustin.hirschi@gmail.com

**Comment by vicmpen** [comment]
vicmpen18@gmail.com

**Comment by Pradeet** [comment]
pradeet1995@gmail.com

**Comment by Go2SleepSoshi** [comment]
ecaflol@gmail.com

**Comment by mpvasilis** [comment]
me[at]vasilis.pw

**Comment by niels-de-witte** [comment]
nielsje153@gmail.com

**Comment by monu11296** [comment]
monu11296@gmail.com

**Comment by Pierre12321** [comment]
thorin_oakeenshield@hotmail.Com

**Comment by Aman-1412** [comment]
sagravat@gmail.com

**Comment by sohamt** [comment]
sohamtrivedi92@gmail.com

**Comment by jaoropeza** [comment]
aoropezauribe@gmail.com

**Comment by ManojMadanmohan** [comment]
manoj.madanmohan@gmail.com

**Comment by nadakbar** [comment]
nadeemakbar786@gmail.com

**Comment by sbarrack** [comment]
stephen.barrack12@gmail.com

**Comment by agusschooven** [comment]
Agusschooven@gmail.com

**Comment by Zikkoua** [comment]
zikkoua@gmail.com  Android Developer

**Comment by traendy** [comment]
peters.soenke@gmail.com

**Comment by 0legg** [comment]
olegg.lieangel@gmail.com

**Comment by stephenhyde** [comment]
stephenhyde@gmail.com

**Comment by Chirag-Galani** [comment]
chiraggalani25@gmail.com

**Comment by jLynx** [comment]
Email removed

**Comment by neissa** [comment]
kisscool2a@gmail.com

**Comment by axsddlr** [comment]
dresadd09691@gmail.com

**Comment by youdie000** [comment]
youdie000@gmail.com

**Comment by devanshk** [comment]
devanshkukreja1@gmail.com

**Comment by ephidrine** [comment]
yashsharma94@gmail.com
Thank you.

**Comment by LomotMyasa** [comment]
Nikita152r@gmail.com

**Comment by shengjianmantou** [comment]
bigjoker@gmail.com

**Comment by ariviere** [comment]
antoine@riviere.tf

**Comment by tuveldavix** [comment]
Crdafix@gmail.com

**Comment by mikepenz** [comment]
mikepenz@gmail.com

**Comment by Kolyall** [comment]
kolyall@tut.by

**Comment by hakaari** [comment]
javakhidze.giorgi@gmail.com

**Comment by arabianknight1138** [comment]
suntzudo21@gmail.com

**Comment by Ravisdo** [comment]
patrick-werner@live.de

**Comment by Everis** [comment]
furmik@gmail.com

**Comment by guillaumedev** [comment]
contact@guillaumedev.com

**Comment by mortmafaka** [comment]
mortmafaka@gmail.com

**Comment by lhuelsmann** [comment]
lhuedev@gmail.com

**Comment by sameerbatavia** [comment]
sameer.batavia@gmail.com

**Comment by Mensch88** [comment]
yujian5@gmail.com

**Comment by anton46** [comment]
anton.work19@gmail.com

**Comment by rahulvyas1** [comment]
rahul.basketball@yahoo.co.in

**Comment by shrey150** [comment]
shrey150@yahoo.com

**Comment by chrosey** [comment]
christian.seyfferth@gmail.com

**Comment by Nehri** [comment]
kyuraii@gmail.com

**Comment by ZeroThe2nd** [comment]
nightfireluna@gmail.com
Ready to help with 6.x testing ^^

**Comment by voidc** [comment]
dominik.stolz21@gmail.com

**Comment by mzusman** [comment]
morzusman@gmail.com

**Comment by agastimhatre** [comment]
agastimhatre@gmail.com

**Comment by pteacher** [comment]
subfear@mail.ru

**Comment by nkcheng255** [comment]
desource1990@yahoo.com

**Comment by Kam1-kaz3** [comment]
salman102@gmail.com

**Comment by garreyxu** [comment]
garreyxu@gmail.com

**Comment by Miolav** [comment]
savinykh.va@gmail.com

**Comment by Timorleiderman** [comment]
timorleiderman@gmail.com

**Comment by aslafy-z** [comment]
WTF ?! Are you serious about exposing all of these email like that ?

Please use this instead: [https://github.com/rauchg/slackin](https://github.com/rauchg/slackin)

**Comment by Night111221** [comment]
Wait really wym he exposing all these emails!

**Comment by stijndebacker** [comment]
stijndebacker@me.com

**Comment by andycervantes** [comment]
gundam00692000@yahoo.com

**Comment by bastianjoel** [comment]
info@bastianjoel.de

**Comment by caniev** [comment]
Canievking@gmail.com

**Comment by aznvamp** [comment]
aznvamp@gmail.com

**Comment by boriswtam** [comment]
bobo22slo@gmail.com

**Comment by roadev** [comment]
jdroa92@gmail.com

**Comment by nekoboy93** [comment]
nekoboy93@outlook.com

**Comment by OsirisFrik** [comment]
osiris.lpz96@gmail.com

**Comment by niklaswa** [comment]
github@niklas.top

**Comment by siaziz** [comment]
siaz1z@yahoo.com

**Comment by AEfremov** [comment]
alexandr.efremoff@gmail.com

**Comment by Marsonge** [comment]
tim.caillot@gmail.com

**Comment by KyuremBoG** [comment]
denic190499@gmail.com

**Comment by CryZerR** [comment]
cryzer66@gmail.com

**Comment by thiagoafram** [comment]
thiago_silva@hotmail.com

**Comment by XxK1llingD3ath** [comment]
benarnott52@gmail.com

**Comment by brusus** [comment]
raffa-93@hotmail.it

**Comment by murych** [comment]
murychkun@yahoo.com

**Comment by zeuslalit** [comment]
zeuslalit@gmail.com

**Comment by AdrianAldea** [comment]
suntadrian@gmail.com

**Comment by ghost** [comment]
phonglanhuong.center@gmail.com
