### ISSUE TITLE
Not shown any pokemon or pokestop or gym

### ISSUE THREAD

**Issue by pgoh4xor** [omkarmoghe/Pokemap#57]
Installed the app-debug.apk to mobile with Android 6.0.1.
Used a newly created PTC account. The new account data works fine with main python-flask code.
But I am not able to see anything on map. I have checked show pokestop and gym also. 
Only seeing my location as blue dot in map. How to check if there is any problem ?

**Comment by N3evin** [comment]
This app is still under development. Therefore no images and location are available right now. Do wait for further development.

**Comment by boginw** [comment]
We should make it more obvious that no pokemons are showing yet in the README. Maybe large bold letters
