### ISSUE TITLE
Pokemon locations

### ISSUE THREAD

**Issue by ZakharchenkoWork** [omkarmoghe/Pokemap#6]
I could try to recreate functionality from main repo but i'm not familliar with "Py". can somebody tell me where to search for the code, which is grabing pokemons list?

**Comment by omkarmoghe** [comment]
Check the getPokemon() method. There's a link to the relavent code in the javadoc comment.

**Comment by rohanjain1** [comment]
I'm in the same boat, i found the py code, but have no experience in decoding protos, keep looking for solid DOMs throughout the quick and dirty code. -.- habits..
Anyways, i'd love to start contributing to this project as time goes on, hopefully i'll get some help from you guys. 
I can start adding some stuff just as soon as someone can get me a nearby pokemon list. 
top on my list of TO-DOs:
-filters
-ability to Disable scheduled heartbeats. Allow re-fetch on button click. (Major Battery saver)
-alerts (might need to discuss if a background service for the entire heartbeat logic is a good idea. i hate the battery drain)
-color-coding as per time remaining
-startup sequence (startup time is too high for my taste)

@ZakharchenkoWork : check the parent project. It's already deployed and working for desktop. 

Looking forward to working with you guys.
Cheers,
Rohan

**Comment by omkarmoghe** [comment]
@rohanjain1 dope, feel free to join the slack to stay updated on stuff we're working on

**Comment by mozarty** [comment]
Hey Guys , the slack channel has its limit reached .

i wanna help anyway i can , let me know if you need another contributor

**Comment by omkarmoghe** [comment]
what's your email?

**Comment by mozarty** [comment]
mozarty11@gmail.com

**Comment by omkarmoghe** [comment]
@mozarty :/ people need to accept the ones we've sent out. still wont let me add people. sorry!

**Comment by psamsonov** [comment]
Maybe try an IRC channel instead.
