### ISSUE TITLE
Why Android Studio 2.2 Preview 1 as opposed to [stable]Android Studio 2.1.2?

### ISSUE THREAD

**Issue by JDMcKinstry** [omkarmoghe/Pokemap#61]
Hopefully these questions are properly appropriated here, if not, just let me know and I'll shuffle things around respectively.
Thank you for your time if you take time to read all these questions! :)
I'm curious, as I like to know the "5 W's & H", or at least most of them of most things. If it's OK, I have a few questions about this I don't see fully answered here.
So I have to ask, any reason why it has to be the unstable 2.2 version which is, as I just found out, tedious to find direct download link on. I found it, [here btw](http://tools.android.com/download/studio/builds/android-studio-2-2-preview-1), it was just a little annoying to find, and I'm not to fond, as I've been rubbed the wrong way with other IDE's, of using "preview" or "beta" versions of IDE's.
Are you aware of why it can't work in public, official release version 2.1?
What alternatives could be made using 2.1 as opposed to 2.2?
How might one apply such alternatives?
Will there be a prepacked build of this apk released or is it intended as self build only?
And, as you may have guessed, I'm a bit new to Android coding, I'd like to know the quick and ugly summary of how one might be able to check that there's no "underhanded" code in this before building and using? In other words, and I'll google this more later and see what I find, however I find it never hurts to ask in places like this, what areas (directories/files) can I look at to see if the original builder, or append builder added something like a keylogger or other such "evil purpose"?
Oh and one last thought, any chance this might receive some support with self-answered Q&A's (from current builders and users of course) on a Stack Exchange channel such as stackoverflow.com? With that in mind, do any of the Authors on this project have SE accounts and have they considered watching such sites for further questions which may help provide better future documentation?
Again, thank you for your time.

**Comment by s7092910** [comment]
Probably because of the Constraint Layout. As it only works in Android Studio 2.2

**Comment by JDMcKinstry** [comment]
@s7092910 Thanks for that bit. I assume what you're referring to is [**this**](http://tools.android.com/tech-docs/layout-editor)?

**Comment by CanOrhan** [comment]
@s7092910 That ConstraintLayout was removed in PR #20: https://github.com/omkarmoghe/Pokemap/pull/20/files#diff-4da4ec296a1d2b408af6ab9ce4f2b11f

**Comment by s7092910** [comment]
@CanOrhan Ah I see, it wasn't mentioned in a commit so I didn't notice it.

**Comment by Silenc3IsGold3n** [comment]
I got the dev version built properly on 2.1

**Comment by Silenc3IsGold3n** [comment]
Alpha*

**Comment by comann** [comment]
This limitation is now lifted in the dev branch. Previously the project depended on constraintlayout.

**Comment by omkarmoghe** [comment]
Right, _should_ be able to build on 2.1 releases. @JDMcKinstry can you try building it on 2.1 and let us know? there's no real reason besides the constraint layout that were auto generated, but we have since removed that.

**Comment by comann** [comment]
Can this be closed now?
