### ISSUE TITLE
PokeGOAPI Gradle Build Error

### ISSUE THREAD

**Issue by s7092910** [omkarmoghe/Pokemap#66]
`Error:Could not find com.github.Grover-c13:PokeGOAPI-Java:master-SNAPSHOT.
Required by:
    Pokemap:app:unspecified`

I'm getting the above error on the dev branch. Not sure if it is just me or not. Anyways anyone have any ideas how to fix it. Both build.gradle files are unedited from the dev branch.

**Comment by s7092910** [comment]
Also it might be better to use a jar, that way the dependency isn't constantly changing. Just in case the PokeGOAPI changes some of the behavior of the app.

**Comment by comann** [comment]
Due to the nature of what this project is trying to achieve, its necessary to keep on the edge. 

For now, you can use this:

```
compile 'com.github.Grover-c13:PokeGOAPI-Java:4f5b715380'
```

[We have filed an issue with there repo.](https://github.com/Grover-c13/PokeGOAPI-Java/issues/139)

**Comment by omkarmoghe** [comment]
fixed with #67
