### ISSUE TITLE
Rotation forces map reloading (GPS position refreshing)

### ISSUE THREAD

**Issue by Jertlok** [omkarmoghe/Pokemap#69]
Hi there, this project is evolving fastly, good job devs! 
Today I noticed that as soon as I rotate my screen the application reloads the map getting my position and showing the toast notification "Found you".

Cheers.

**Comment by omkarmoghe** [comment]
@Jertlok interesting. will look into this. thanks for the feedback!

**Comment by comann** [comment]
Also constant toasting too.

**Comment by ManojMadanmohan** [comment]
@omkarmoghe can this be closed now?
