### ISSUE TITLE
Permission request code can only use lower 8 bits (MapWrapperFragment)

### ISSUE THREAD

**Issue by Krisztiaan** [omkarmoghe/Pokemap#7]
The error is on `MapWrapperFragment:39`
The int should be from 0 to 255, otherwise it will crash with
`java.lang.IllegalArgumentException: Can only use lower 8 bits for requestCode`

**Comment by kutukoff** [comment]
```
private static final int LOCATION_PERMISSION_REQUEST = 703;
```

to 

```
private static final int LOCATION_PERMISSION_REQUEST = 19;
```

**Comment by omkarmoghe** [comment]
Good catch!
