### ISSUE TITLE
Android 6.x.x

### ISSUE THREAD

**Issue by ZeroThe2nd** [omkarmoghe/Pokemap#72]
Hi team,

Didn't know where to put this, but I've got an Xperia Z3 Compact running android 6.0.1. I'm not an android dev (yet), but I was looking through the code and saw a TODO saying you needed to

> test all this shit on a 6.0+ phone lmfao

If needed, I can help with that ^-^

**Comment by omkarmoghe** [comment]
@ZeroThe2nd awesome! we have it set up to build apks on each build. post in #56 to join our slack and we could def use some help with testing!
