### ISSUE TITLE
Can't Log Into Account After Entering Credentials

### ISSUE THREAD

**Issue by jmrapp1** [omkarmoghe/Pokemap#76]
If you enter credentials and they are incorrect, there is no way to change them unless you uninstall and reinstall the application.

**Comment by wjwolf79** [comment]
#63 Addresses this issue

**Comment by omkarmoghe** [comment]
lol good catch

**Comment by vidarr101** [comment]
Just added a pull request for this.

**Comment by MikePT28** [comment]
If this is solved please close the issue.

@omkarmoghe
