### ISSUE TITLE
Lowest API version (at least 21)

### ISSUE THREAD

**Issue by zyxer** [omkarmoghe/Pokemap#8]
How about changing API version to lowest one?
If it's only about material design button and so on, it'll be more useful to bring this app for more people. (for example me with friends have Lollipop androids, and we are not the one with this 'old' version, I think)

**Comment by Jawnnypoo** [comment]
The min version right now is 17 (4.2) so I am not sure what the issue is

**Comment by omkarmoghe** [comment]
Right are you asking to bump min up or lower it further? Either way it works on lollipop

**Comment by zyxer** [comment]
I'm sorry, huge omit happens here :S 
Right, min ver = 17, but I've got err 'unfortunately application has stopped' without any info.
Maybe I've done somethink wrong, can someone put apk on gdrive/other?

**Comment by Jawnnypoo** [comment]
Yes, the current code has an error that makes it crash on launch, it is unrelated to the minSdk though

**Comment by zyxer** [comment]
I got it. Can I recive old commit without error?
Or I need wait for other stable version?

**Comment by omkarmoghe** [comment]
@zyxer you need to add your username and password to the `getToken` method. I updated the Readme. Sorry for the instability of this build. I didnt have time to add much error handling. Just pushed a basic skeleton so that contributors have somewhere to submit PRs to

**Comment by zyxer** [comment]
@omkarmoghe thanks, it works, and now I can try to dig this mine :)
