### ISSUE TITLE
seems Working 

### ISSUE THREAD

**Issue by pokecatchy** [omkarmoghe/Pokemap#82]
Hi after forking yesterday i got an acceptable version now incremtally bringing up the pokes around 
maybe have a look at it, fork it, build it, reintegrate it and post it  
thanks to all providing the base for it 

btw. its written most crappy. in my defense i dont usually develop java or apps ...

**Comment by kyr0** [comment]
Hi, thanks a lot, I would like to try it out but I get compilation errors. getSpawnPointId is missing:

Inside of the IDE (Android Studio 2.2) the method is _partly_ recognized. Auto-completion knows the method doesn't complain (decompile shows the method too), but syntax check points out that the method is missing and so does the grade build:

/Users/.../Source/StudioProjects/Pokemap_working/app/src/main/java/com/omkarmoghe/pokemap/map/MapWrapperFragment.java
Error:(182, 20) error: cannot find symbol method getSpawnpointId()
/Users/.../Source/StudioProjects/Pokemap_working/app/src/main/java/com/omkarmoghe/pokemap/map/Pokemon.java
Error:(30, 24) error: cannot find symbol method getSpawnpointId()
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.

> Compilation failed; see the compiler error output for details.
> Information:BUILD FAILED

 Am I missing some step in configuration or ProtoBuf compiling?

**Comment by pokecatchy** [comment]
you have used the poke radar brabnch do you ?

**Comment by pokecatchy** [comment]
yes proto puffs need to compile .. but its built in in gradle

**Comment by kyr0** [comment]
I've used your fork: https://github.com/pokecatchy/Pokemap and branch: poke_radar, yep :) 
Should I switch to another one?

**Comment by kyr0** [comment]
I have Android Studio 2.2. Preview 6; "android plugin for gradle version": 2.2.0-alpha6 (the IDE complained that Instant Run would not work otherwise); "gradle version": 2.10

**Comment by pokecatchy** [comment]
Androidstudio 2.1.2  and gradle 143 plugin 
gradle 2.1.2

**Comment by pokecatchy** [comment]
yea i disabled instant run

**Comment by kyr0** [comment]
Okay, thanks I will try again using this setup and let you know the results.
Is there anything apart from "Makeing the project" and "Debug" target "app" that I should take care of? ;)

**Comment by omkarmoghe** [comment]
ayy :fire:

**Comment by pokecatchy** [comment]
not sure why it didn't work but the build chain seems odd anyway ... as said before my first real android project and java since 2005 

only known issu is that it  would be great if the settings would actually be displayed .. but they are set and can be edited 
also it just came up when building release that it needs multidex ... so i added that for releasing

**Comment by kyr0** [comment]
Hmm, well :) Now I have the same setup like you but still I'm getting this compilation error. Hmm I will try out some hacks now... :)

**Comment by kyr0** [comment]
Okay, I have no idea why, but now it works. And WOW! This is cool!

What I did was:
- Installing additional SDK Platforms: 6.0, 5.1 (I had 6.x, 5.0 before) via the SDK manager
- Installing additional SDK Tools: Android SDK Build Tools, CMake 3.6, Google Play Services, LLDB, NDK
- Android Studio -> File -> Invalidate Caches / Restart -> Invalidate, Restart

After restart build and APK install just works fine.
Thank you, that looks great.

Now I would like to contribute some code. I'm familiar with Java and a bit with Android (already wrote some small Apps) -- not familiar with Protobuf but thats not so hard to grasp...

Do you have any tasks for me? :)

**Comment by pokecatchy** [comment]
there was a typo fix provided an i pulled in ... however i could not verify that it works ...

**Comment by pokecatchy** [comment]
finally it's working ...
