### ISSUE TITLE
Official APK

### ISSUE THREAD

**Issue by peter6006** [omkarmoghe/Pokemap#86]
Hi, im working in something that you guys are doing, but you are tons of hours ahead and my questions are, are you planning on publish it to Google Play Store? which funcionalities are you planning to code?

**Comment by pokecatchy** [comment]
i doubt playstore will embrace that

**Comment by peter6006** [comment]
There are several maps like this one (pokevision for example), meanwhile this apk does not transform into a bot, i think its ok.

**Comment by wjwolf79** [comment]
The entire concept of this app (fetching pokemon locations outside of the official PokemonGo app), is a violation of the TOS for the game.  It will not be ok on the playstore.

**Comment by IchigoWalker** [comment]
https://play.google.com/store/apps/details?id=berlog.develop.guid.by.pokefind
This is what your app about. Live pokemon map. Not banned (published 1 day ago).

**Comment by wjwolf79** [comment]
not banned yet.  I guarantee Niantic will have it taken down, and the developer will probably be issued a cease and desist order.

**Comment by omkarmoghe** [comment]
see https://github.com/omkarmoghe/Pokemap/releases for now.

**Comment by ghost** [comment]
@IchigoWalker there are no bots in app, bots running on remote server, an we are finding poks, not pokemons :D
