### ISSUE TITLE
quirk timestamp

### ISSUE THREAD

**Issue by pokecatchy** [omkarmoghe/Pokemap#89]
the expiration is not allways unixtimeMS sometimes its only ms till expired .. that results in insane days in view ...

**Comment by pokecatchy** [comment]
see Pokemap/app/src/main/java/com/omkarmoghe/pokemap/map/Pokemon.java for how i "solved" it

**Comment by MikePT28** [comment]
This was discussed. Actually the list of pokemons has duplicates of each pokemon. One pokemon has an absolute timestamp and the other one just the ms left. This is supposed to be fixed by PR #132 of the PoGo API. Though a I believe a workaround is in place at the moment.
