### ISSUE TITLE
Need to handle finding lure and mist pokemon

### ISSUE THREAD

**Issue by comann** [omkarmoghe/Pokemap#94]
I'm fairly certain that there are different calls into pokegoapi for these Pokemon.

**Comment by Mahonster** [comment]
mist pokemon?

I'm assuming you mean incense, in which case I believe that Pokemon spawned by incense can only be seen by the user who activated it..

**Comment by silverAndroid** [comment]
I believe he means incense

**Comment by chrosey** [comment]
is it important to show these? i mean, these pokemon are only visible for the user that is in range to catch them. 
So there would be ne need to know how to get there

**Comment by socrates2510** [comment]
You can see a lured pokémon in a pokestop, a rare one and run there to get it. Not that important but useful.

**Comment by chrosey** [comment]
Okay that would make sense for lured Pokéstop monsters at least.

**Comment by s7092910** [comment]
Added in #272. Unfortunately there is no way to get incense/mist pokemon.
