### ISSUE TITLE
What about an UI only App without the full server part?

### ISSUE THREAD

**Issue by Bitti09** [omkarmoghe/Pokemap#99]
Woulnd't it be better to let the "PokemonGo-Map servers" do the search and save job and the apk just  needs to connect to them for  getting the data ?

**Comment by wjwolf79** [comment]
that is what this app does.

Steps: (in a nutshell)
1) Login to account
2) Tell Pogo server where you're at.
3) get nearby pokemon from server
4) display nearby pokemon on map.

**Comment by Aldo-f** [comment]
But it should store the data?

If I search somewhere, and i see a Pokemon disappearing in 5 min, then i do a new search (at onother place) the already searched Pokemon isn't displayed anymore.

Also when more people in the neighborhood search at the same place, you see Pokemons that they have found.
(see https://pokevision.com/#/@51.05617844110523,3.720030784606933 )

**Comment by wjwolf79** [comment]
this app won't show you nearby pokemon from other users.  Pokevision can because it's a web service their doing (where you don't even have to log in)

I do agree that already found pokemon from your search shouldn't be cleared when doing a new search.

**Comment by omkarmoghe** [comment]
@Bitti09 so to answer your original question, we would have to have a central instance of the PokemonGo-Map server running 24/7 for the app to be able to connect to it. The current structure ensures the app runs independently without being dependent on any external server (except Niantic's of course)
